// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: restaurants.proto

// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative restaurants.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetRestaurantService_GetRestaurant_FullMethodName = "/protobuf.GetRestaurantService/GetRestaurant"
)

// GetRestaurantServiceClient is the client API for GetRestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetRestaurantServiceClient interface {
	GetRestaurant(ctx context.Context, in *GetRestaurantReq, opts ...grpc.CallOption) (*Restaurant, error)
}

type getRestaurantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetRestaurantServiceClient(cc grpc.ClientConnInterface) GetRestaurantServiceClient {
	return &getRestaurantServiceClient{cc}
}

func (c *getRestaurantServiceClient) GetRestaurant(ctx context.Context, in *GetRestaurantReq, opts ...grpc.CallOption) (*Restaurant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Restaurant)
	err := c.cc.Invoke(ctx, GetRestaurantService_GetRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRestaurantServiceServer is the server API for GetRestaurantService service.
// All implementations must embed UnimplementedGetRestaurantServiceServer
// for forward compatibility.
type GetRestaurantServiceServer interface {
	GetRestaurant(context.Context, *GetRestaurantReq) (*Restaurant, error)
	mustEmbedUnimplementedGetRestaurantServiceServer()
}

// UnimplementedGetRestaurantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetRestaurantServiceServer struct{}

func (UnimplementedGetRestaurantServiceServer) GetRestaurant(context.Context, *GetRestaurantReq) (*Restaurant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurant not implemented")
}
func (UnimplementedGetRestaurantServiceServer) mustEmbedUnimplementedGetRestaurantServiceServer() {}
func (UnimplementedGetRestaurantServiceServer) testEmbeddedByValue()                              {}

// UnsafeGetRestaurantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetRestaurantServiceServer will
// result in compilation errors.
type UnsafeGetRestaurantServiceServer interface {
	mustEmbedUnimplementedGetRestaurantServiceServer()
}

func RegisterGetRestaurantServiceServer(s grpc.ServiceRegistrar, srv GetRestaurantServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetRestaurantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetRestaurantService_ServiceDesc, srv)
}

func _GetRestaurantService_GetRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetRestaurantServiceServer).GetRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetRestaurantService_GetRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetRestaurantServiceServer).GetRestaurant(ctx, req.(*GetRestaurantReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GetRestaurantService_ServiceDesc is the grpc.ServiceDesc for GetRestaurantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetRestaurantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.GetRestaurantService",
	HandlerType: (*GetRestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurant",
			Handler:    _GetRestaurantService_GetRestaurant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restaurants.proto",
}

const (
	GetRestaurantBranchService_GetRestaurantBranch_FullMethodName = "/protobuf.GetRestaurantBranchService/GetRestaurantBranch"
)

// GetRestaurantBranchServiceClient is the client API for GetRestaurantBranchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetRestaurantBranchServiceClient interface {
	GetRestaurantBranch(ctx context.Context, in *GetRestaurantBranchReq, opts ...grpc.CallOption) (*Restaurant, error)
}

type getRestaurantBranchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetRestaurantBranchServiceClient(cc grpc.ClientConnInterface) GetRestaurantBranchServiceClient {
	return &getRestaurantBranchServiceClient{cc}
}

func (c *getRestaurantBranchServiceClient) GetRestaurantBranch(ctx context.Context, in *GetRestaurantBranchReq, opts ...grpc.CallOption) (*Restaurant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Restaurant)
	err := c.cc.Invoke(ctx, GetRestaurantBranchService_GetRestaurantBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRestaurantBranchServiceServer is the server API for GetRestaurantBranchService service.
// All implementations must embed UnimplementedGetRestaurantBranchServiceServer
// for forward compatibility.
type GetRestaurantBranchServiceServer interface {
	GetRestaurantBranch(context.Context, *GetRestaurantBranchReq) (*Restaurant, error)
	mustEmbedUnimplementedGetRestaurantBranchServiceServer()
}

// UnimplementedGetRestaurantBranchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetRestaurantBranchServiceServer struct{}

func (UnimplementedGetRestaurantBranchServiceServer) GetRestaurantBranch(context.Context, *GetRestaurantBranchReq) (*Restaurant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantBranch not implemented")
}
func (UnimplementedGetRestaurantBranchServiceServer) mustEmbedUnimplementedGetRestaurantBranchServiceServer() {
}
func (UnimplementedGetRestaurantBranchServiceServer) testEmbeddedByValue() {}

// UnsafeGetRestaurantBranchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetRestaurantBranchServiceServer will
// result in compilation errors.
type UnsafeGetRestaurantBranchServiceServer interface {
	mustEmbedUnimplementedGetRestaurantBranchServiceServer()
}

func RegisterGetRestaurantBranchServiceServer(s grpc.ServiceRegistrar, srv GetRestaurantBranchServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetRestaurantBranchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetRestaurantBranchService_ServiceDesc, srv)
}

func _GetRestaurantBranchService_GetRestaurantBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantBranchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetRestaurantBranchServiceServer).GetRestaurantBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetRestaurantBranchService_GetRestaurantBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetRestaurantBranchServiceServer).GetRestaurantBranch(ctx, req.(*GetRestaurantBranchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GetRestaurantBranchService_ServiceDesc is the grpc.ServiceDesc for GetRestaurantBranchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetRestaurantBranchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.GetRestaurantBranchService",
	HandlerType: (*GetRestaurantBranchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantBranch",
			Handler:    _GetRestaurantBranchService_GetRestaurantBranch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restaurants.proto",
}

const (
	SearchRestaurantsService_SearchRestaurants_FullMethodName = "/protobuf.SearchRestaurantsService/SearchRestaurants"
)

// SearchRestaurantsServiceClient is the client API for SearchRestaurantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchRestaurantsServiceClient interface {
	SearchRestaurants(ctx context.Context, in *SearchRestaurantsReq, opts ...grpc.CallOption) (*Restaurants, error)
}

type searchRestaurantsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchRestaurantsServiceClient(cc grpc.ClientConnInterface) SearchRestaurantsServiceClient {
	return &searchRestaurantsServiceClient{cc}
}

func (c *searchRestaurantsServiceClient) SearchRestaurants(ctx context.Context, in *SearchRestaurantsReq, opts ...grpc.CallOption) (*Restaurants, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Restaurants)
	err := c.cc.Invoke(ctx, SearchRestaurantsService_SearchRestaurants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchRestaurantsServiceServer is the server API for SearchRestaurantsService service.
// All implementations must embed UnimplementedSearchRestaurantsServiceServer
// for forward compatibility.
type SearchRestaurantsServiceServer interface {
	SearchRestaurants(context.Context, *SearchRestaurantsReq) (*Restaurants, error)
	mustEmbedUnimplementedSearchRestaurantsServiceServer()
}

// UnimplementedSearchRestaurantsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchRestaurantsServiceServer struct{}

func (UnimplementedSearchRestaurantsServiceServer) SearchRestaurants(context.Context, *SearchRestaurantsReq) (*Restaurants, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRestaurants not implemented")
}
func (UnimplementedSearchRestaurantsServiceServer) mustEmbedUnimplementedSearchRestaurantsServiceServer() {
}
func (UnimplementedSearchRestaurantsServiceServer) testEmbeddedByValue() {}

// UnsafeSearchRestaurantsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchRestaurantsServiceServer will
// result in compilation errors.
type UnsafeSearchRestaurantsServiceServer interface {
	mustEmbedUnimplementedSearchRestaurantsServiceServer()
}

func RegisterSearchRestaurantsServiceServer(s grpc.ServiceRegistrar, srv SearchRestaurantsServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchRestaurantsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchRestaurantsService_ServiceDesc, srv)
}

func _SearchRestaurantsService_SearchRestaurants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRestaurantsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchRestaurantsServiceServer).SearchRestaurants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchRestaurantsService_SearchRestaurants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchRestaurantsServiceServer).SearchRestaurants(ctx, req.(*SearchRestaurantsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchRestaurantsService_ServiceDesc is the grpc.ServiceDesc for SearchRestaurantsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchRestaurantsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.SearchRestaurantsService",
	HandlerType: (*SearchRestaurantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchRestaurants",
			Handler:    _SearchRestaurantsService_SearchRestaurants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restaurants.proto",
}
