basePath: /v1/loans
definitions:
  customizegin.APIError:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: integer
    type: object
  customizegin.JSONResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/customizegin.APIError'
      message:
        type: string
      success:
        type: boolean
    type: object
  enums.LoanType:
    enum:
    - invalid
    - home
    - car
    type: string
    x-enum-varnames:
    - LoanTypeInvalid
    - LoanTypeHome
    - LoanTypeCar
  featuresdtos.CreateLoanRequest:
    properties:
      interest_rate:
        description: '@example 0.03'
        type: string
      loan_type:
        allOf:
        - $ref: '#/definitions/enums.LoanType'
        description: '@example "home", "car"'
      mobile_number:
        description: '@example 0958308280'
        type: string
      term:
        description: '@example 84'
        type: integer
      total_amount:
        description: '@example 10000000'
        type: string
    required:
    - interest_rate
    - loan_type
    - mobile_number
    - term
    - total_amount
    type: object
  featuresdtos.DeleteLoanRequest:
    properties:
      id:
        type: string
    type: object
  featuresdtos.GetLoansRequest:
    properties:
      active_switch:
        type: boolean
      mobile_number:
        type: string
    required:
    - mobile_number
    type: object
  featuresdtos.UpdateLoanRequest:
    properties:
      active_switch:
        type: boolean
      id:
        type: string
      interest_rate:
        type: string
      mobile_number:
        type: string
      paid_amount:
        type: string
      term:
        type: integer
      total_amount:
        type: string
    required:
    - id
    type: object
host: localhost:7003
info:
  contact: {}
  description: Simple service for loans resources
  title: Loans Service API
  version: "1.0"
paths:
  /loan/create:
    post:
      consumes:
      - application/json
      description: Create a new loan
      parameters:
      - description: Loan
        in: body
        name: loan
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.CreateLoanRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Loan created successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Create a new loan
      tags:
      - loans
  /loan/delete:
    post:
      description: Delete a loan
      parameters:
      - description: Loan
        in: body
        name: loan
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.DeleteLoanRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Loan deleted successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Delete a loan
      tags:
      - loans
  /loan/update:
    put:
      consumes:
      - application/json
      description: Update an loan
      parameters:
      - description: Loan
        in: body
        name: loan
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.UpdateLoanRequest'
      produces:
      - application/json
      responses:
        "200":
          description: loan updated successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Update an loan
      tags:
      - loans
  /loans/get:
    post:
      description: Get loans by mobile number and active switch
      parameters:
      - description: Loan
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.GetLoansRequest'
      produces:
      - application/json
      responses:
        "200":
          description: loan retrieved successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Get loans by mobile number and active switch
      tags:
      - loans
swagger: "2.0"
