// Code generated by MockGen. DO NOT EDIT.
// Source: loan_number.go
//
// Generated by this command:
//
//	mockgen -source=loan_number.go -destination=./mocks/loan_number_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoanNumberGenerator is a mock of LoanNumberGenerator interface.
type MockLoanNumberGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockLoanNumberGeneratorMockRecorder
	isgomock struct{}
}

// MockLoanNumberGeneratorMockRecorder is the mock recorder for MockLoanNumberGenerator.
type MockLoanNumberGeneratorMockRecorder struct {
	mock *MockLoanNumberGenerator
}

// NewMockLoanNumberGenerator creates a new mock instance.
func NewMockLoanNumberGenerator(ctrl *gomock.Controller) *MockLoanNumberGenerator {
	mock := &MockLoanNumberGenerator{ctrl: ctrl}
	mock.recorder = &MockLoanNumberGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanNumberGenerator) EXPECT() *MockLoanNumberGeneratorMockRecorder {
	return m.recorder
}

// GenerateLoanNumber mocks base method.
func (m *MockLoanNumberGenerator) GenerateLoanNumber() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateLoanNumber")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateLoanNumber indicates an expected call of GenerateLoanNumber.
func (mr *MockLoanNumberGeneratorMockRecorder) GenerateLoanNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateLoanNumber", reflect.TypeOf((*MockLoanNumberGenerator)(nil).GenerateLoanNumber))
}
