basePath: /v1/cards
definitions:
  customizegin.APIError:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: integer
    type: object
  customizegin.JSONResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/customizegin.APIError'
      message:
        type: string
      success:
        type: boolean
    type: object
  featuresdtos.CreateCreditCardRequest:
    properties:
      mobile_number:
        description: '@example 0958308280'
        type: string
      total_limit:
        description: '@example 100000'
        type: string
    required:
    - mobile_number
    - total_limit
    type: object
  featuresdtos.DeleteCreditCardRequest:
    properties:
      id:
        type: string
    type: object
  featuresdtos.GetCreditCardsRequest:
    properties:
      active_switch:
        type: boolean
      mobile_number:
        type: string
    required:
    - mobile_number
    type: object
  featuresdtos.UpdateCreditCardRequest:
    properties:
      amount_used:
        type: string
      id:
        type: string
      mobile_number:
        type: string
      total_limit:
        type: string
    required:
    - id
    type: object
host: localhost:7002
info:
  contact: {}
  description: Simple service for cards resources
  title: Cards Service API
  version: "1.0"
paths:
  /credit-card/create:
    post:
      consumes:
      - application/json
      description: Create a new credit card
      parameters:
      - description: Credit Card
        in: body
        name: credit-card
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.CreateCreditCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Credit Card created successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Create a new credit card
      tags:
      - cards
  /credit-card/delete:
    post:
      description: Delete a credit card
      parameters:
      - description: Credit Card
        in: body
        name: credit-card
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.DeleteCreditCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Credit Card deleted successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Delete a credit card
      tags:
      - cards
  /credit-card/update:
    put:
      consumes:
      - application/json
      description: Update an card
      parameters:
      - description: Card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.UpdateCreditCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: card updated successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Update an card
      tags:
      - cards
  /credit-cards/get:
    post:
      description: Get credit cards by mobile number and active switch
      parameters:
      - description: Credit Card
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.GetCreditCardsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: credit card retrieved successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Get credit cards by mobile number and active switch
      tags:
      - cards
swagger: "2.0"
