// Code generated by MockGen. DO NOT EDIT.
// Source: credit_cards_update_impl.go
//
// Generated by this command:
//
//	mockgen -source=credit_cards_update_impl.go -destination=./mocks/credit_cards_update_impl_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
