basePath: /v1/customers
definitions:
  customizegin.APIError:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: integer
    type: object
  customizegin.JSONResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/customizegin.APIError'
      message:
        type: string
      success:
        type: boolean
    type: object
  featuresdtos.CreateCustomerRequest:
    properties:
      email:
        description: '@example john.doe@example.com'
        type: string
      first_name:
        description: '@example John'
        type: string
      last_name:
        description: '@example Doe'
        type: string
      mobile_number:
        description: '@example 0958308280'
        type: string
    required:
    - email
    - first_name
    - last_name
    - mobile_number
    type: object
  featuresdtos.DeleteCustomerRequest:
    properties:
      id:
        type: string
    type: object
  featuresdtos.GetCustomerRequest:
    properties:
      active_switch:
        type: boolean
      mobile_number:
        type: string
    required:
    - mobile_number
    type: object
  featuresdtos.UpdateCustomerRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      mobile_number:
        type: string
    required:
    - id
    type: object
host: localhost:7003
info:
  contact: {}
  description: Simple service for customers resources
  title: Customers Service API
  version: "1.0"
paths:
  /customer/create:
    post:
      consumes:
      - application/json
      description: Create a new customer
      parameters:
      - description: Customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.CreateCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Customer created successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Create a new customer
      tags:
      - customers
  /customer/delete:
    post:
      description: Delete a customer
      parameters:
      - description: Customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.DeleteCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Customer deleted successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Delete a customer
      tags:
      - customers
  /customer/get:
    post:
      description: Get customer by mobile number and active switch
      parameters:
      - description: Customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.GetCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: customer retrieved successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Get customer by mobile number and active switch
      tags:
      - customers
  /customer/update:
    put:
      consumes:
      - application/json
      description: Update an customer
      parameters:
      - description: Customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/featuresdtos.UpdateCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: customer updated successfully
          schema:
            $ref: '#/definitions/customizegin.JSONResponse'
      summary: Update an customer
      tags:
      - customers
swagger: "2.0"
