// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "Get all categories",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get all categories",
                "responses": {
                    "200": {
                        "description": "categories retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/customizegin.JSONResponse"
                        }
                    }
                }
            }
        },
        "/restaurant/branch/get": {
            "post": {
                "description": "Get restaurant branch by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurants"
                ],
                "summary": "Get restaurant branch by id",
                "parameters": [
                    {
                        "description": "Restaurant Branch",
                        "name": "restaurant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/featuresdtos.GetRestaurantBranchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "restaurant retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/customizegin.JSONResponse"
                        }
                    }
                }
            }
        },
        "/restaurant/get": {
            "post": {
                "description": "Get restaurant by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurants"
                ],
                "summary": "Get restaurant by id",
                "parameters": [
                    {
                        "description": "Restaurant",
                        "name": "restaurant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/featuresdtos.GetRestaurantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "restaurant retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/customizegin.JSONResponse"
                        }
                    }
                }
            }
        },
        "/restaurants/search": {
            "post": {
                "description": "Search restaurants",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurants"
                ],
                "summary": "Search restaurants",
                "parameters": [
                    {
                        "description": "Restaurant",
                        "name": "restaurant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.SearchRestaurants"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "restaurant retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/customizegin.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dtos.Restaurant"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "customizegin.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "customizegin.JSONResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/customizegin.APIError"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "db.OrderBy": {
            "type": "object",
            "properties": {
                "direction": {
                    "$ref": "#/definitions/db.OrderByDirection"
                },
                "field": {
                    "type": "string"
                }
            }
        },
        "db.OrderByDirection": {
            "type": "string",
            "enum": [
                "asc",
                "desc"
            ],
            "x-enum-varnames": [
                "OrderByDirectionAsc",
                "OrderByDirectionDesc"
            ]
        },
        "db.Pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                }
            }
        },
        "dtos.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "$ref": "#/definitions/enums.City"
                },
                "country": {
                    "$ref": "#/definitions/enums.Country"
                },
                "id": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "dtos.Available": {
            "type": "object",
            "properties": {
                "end_time": {
                    "description": "HH:MM",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "start_time": {
                    "description": "HH:MM",
                    "type": "string"
                },
                "weekday": {
                    "$ref": "#/definitions/time.Weekday"
                }
            }
        },
        "dtos.Branch": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/dtos.Address"
                },
                "availables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Available"
                    }
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Category"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price_range": {
                    "$ref": "#/definitions/dtos.PriceRange"
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Table"
                    }
                }
            }
        },
        "dtos.Category": {
            "type": "object",
            "properties": {
                "activeStatus": {
                    "type": "boolean"
                },
                "category": {
                    "$ref": "#/definitions/enums.Category"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                }
            }
        },
        "dtos.PriceRange": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "max_price": {
                    "type": "integer"
                },
                "min_price": {
                    "type": "integer"
                }
            }
        },
        "dtos.Restaurant": {
            "type": "object",
            "properties": {
                "active_status": {
                    "type": "boolean"
                },
                "branches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Branch"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.SearchRestaurants": {
            "type": "object",
            "properties": {
                "branchID": {
                    "type": "string"
                },
                "categoryFilter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/enums.Category"
                    }
                },
                "cityFilter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/enums.City"
                    }
                },
                "countryFilter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/enums.Country"
                    }
                },
                "descriptionFilter": {
                    "type": "string"
                },
                "maxPriceFilter": {
                    "type": "integer"
                },
                "minPriceFilter": {
                    "type": "integer"
                },
                "nameFilter": {
                    "type": "string"
                },
                "namePreciseSearch": {
                    "type": "boolean"
                },
                "orderBy": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.OrderBy"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/db.Pagination"
                },
                "tableAvailableEndTime": {
                    "type": "string"
                },
                "tableAvailableStartTime": {
                    "type": "string"
                },
                "tableAvailableWeek": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/time.Weekday"
                    }
                }
            }
        },
        "dtos.Table": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "enums.Category": {
            "type": "string",
            "enum": [
                "invalid",
                "breakfast",
                "lunch",
                "dinner",
                "snack",
                "dessert",
                "drink",
                "other",
                "italian",
                "japanese",
                "korean",
                "chinese",
                "american",
                "mexican",
                "thai",
                "vietnamese",
                "indian",
                "french",
                "german",
                "spanish",
                "brazilian",
                "taiwanese"
            ],
            "x-enum-varnames": [
                "CategoryInvalid",
                "CategoryBreakfast",
                "CategoryLunch",
                "CategoryDinner",
                "CategorySnack",
                "CategoryDessert",
                "CategoryDrink",
                "CategoryOther",
                "CategoryItalian",
                "CategoryJapanese",
                "CategoryKorean",
                "CategoryChinese",
                "CategoryAmerican",
                "CategoryMexican",
                "CategoryThai",
                "CategoryVietnamese",
                "CategoryIndian",
                "CategoryFrench",
                "CategoryGerman",
                "CategorySpanish",
                "CategoryBrazilian",
                "CategoryTaiwanese"
            ]
        },
        "enums.City": {
            "type": "string",
            "enum": [
                "invalid",
                "taipei",
                "new_taipei",
                "taoyuan",
                "taichung",
                "tainan",
                "kaohsiung",
                "hsinchu",
                "keelung",
                "chiayi",
                "miaoli",
                "changhua",
                "nantou",
                "douliu",
                "pingtung",
                "yilan",
                "hualien",
                "taitung",
                "magong",
                "puzi",
                "taibao",
                "toufen",
                "yuanlin",
                "zhubei"
            ],
            "x-enum-comments": {
                "CityChanghua": "彰化市 Zhānghuà Shì",
                "CityChiayi": "嘉義市 Jiāyì Shì",
                "CityDouliu": "斗六市 Dǒuliù Shì",
                "CityHsinchu": "新竹市 Xīnzhú Shì",
                "CityHualien": "花蓮市 Huālián Shì",
                "CityKaohsiung": "高雄市 Gāoxióng Shì",
                "CityKeelung": "基隆市 Jīlóng Shì",
                "CityMagong": "馬公市 Mǎgōng Shì",
                "CityMiaoli": "苗栗市 Miáolì Shì",
                "CityNantou": "南投市 Nántóu Shì",
                "CityNewTaipei": "新北市 Xīnběi Shì",
                "CityPingtung": "屏東市 Píngdōng Shì",
                "CityPuzi": "朴子市 Púzǐ Shì",
                "CityTaibao": "太保市 Tàibǎo Shì",
                "CityTaichung": "臺中市 Táizhōng Shì",
                "CityTainan": "臺南市 Táinán Shì",
                "CityTaipei": "臺北市 Táiběi Shì",
                "CityTaitung": "臺東市 Táidōng Shì",
                "CityTaoyuan": "桃園市 Táoyuán Shì",
                "CityToufen": "頭份市 Tóufèn Shì",
                "CityYilan": "宜蘭市 Yílán Shì",
                "CityYuanlin": "員林市 Yuánlín Shì",
                "CityZhubei": "竹北市 Zhúběi Shì"
            },
            "x-enum-varnames": [
                "CityInvalid",
                "CityTaipei",
                "CityNewTaipei",
                "CityTaoyuan",
                "CityTaichung",
                "CityTainan",
                "CityKaohsiung",
                "CityHsinchu",
                "CityKeelung",
                "CityChiayi",
                "CityMiaoli",
                "CityChanghua",
                "CityNantou",
                "CityDouliu",
                "CityPingtung",
                "CityYilan",
                "CityHualien",
                "CityTaitung",
                "CityMagong",
                "CityPuzi",
                "CityTaibao",
                "CityToufen",
                "CityYuanlin",
                "CityZhubei"
            ]
        },
        "enums.Country": {
            "type": "string",
            "enum": [
                "invalid",
                "taiwan"
            ],
            "x-enum-varnames": [
                "CountryInvalid",
                "CountryTaiwan"
            ]
        },
        "featuresdtos.GetRestaurantBranchRequest": {
            "type": "object",
            "required": [
                "branch_id"
            ],
            "properties": {
                "branch_id": {
                    "type": "string"
                }
            }
        },
        "featuresdtos.GetRestaurantRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "time.Weekday": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                0,
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "x-enum-varnames": [
                "Sunday",
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday",
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/v1/restaurants",
	Schemes:          []string{},
	Title:            "Restaurants Service API",
	Description:      "Simple service for restaurants resources",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
