// Code generated by MockGen. DO NOT EDIT.
// Source: restaurants.go
//
// Generated by this command:
//
//	mockgen -source=restaurants.go -destination=./mocks/restaurants_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	aggregates "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/aggregates"
	dtos "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/dtos"
	entities "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchRestaurantsFullInfo is a mock of SearchRestaurantsFullInfo interface.
type MockSearchRestaurantsFullInfo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRestaurantsFullInfoMockRecorder
	isgomock struct{}
}

// MockSearchRestaurantsFullInfoMockRecorder is the mock recorder for MockSearchRestaurantsFullInfo.
type MockSearchRestaurantsFullInfoMockRecorder struct {
	mock *MockSearchRestaurantsFullInfo
}

// NewMockSearchRestaurantsFullInfo creates a new mock instance.
func NewMockSearchRestaurantsFullInfo(ctrl *gomock.Controller) *MockSearchRestaurantsFullInfo {
	mock := &MockSearchRestaurantsFullInfo{ctrl: ctrl}
	mock.recorder = &MockSearchRestaurantsFullInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRestaurantsFullInfo) EXPECT() *MockSearchRestaurantsFullInfoMockRecorder {
	return m.recorder
}

// SearchRestaurantsFullInfo mocks base method.
func (m *MockSearchRestaurantsFullInfo) SearchRestaurantsFullInfo(ctx context.Context, searchRestaurants *dtos.SearchRestaurants) (aggregates.Restaurants, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRestaurantsFullInfo", ctx, searchRestaurants)
	ret0, _ := ret[0].(aggregates.Restaurants)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRestaurantsFullInfo indicates an expected call of SearchRestaurantsFullInfo.
func (mr *MockSearchRestaurantsFullInfoMockRecorder) SearchRestaurantsFullInfo(ctx, searchRestaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRestaurantsFullInfo", reflect.TypeOf((*MockSearchRestaurantsFullInfo)(nil).SearchRestaurantsFullInfo), ctx, searchRestaurants)
}

// MockRestaurants is a mock of Restaurants interface.
type MockRestaurants struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantsMockRecorder
	isgomock struct{}
}

// MockRestaurantsMockRecorder is the mock recorder for MockRestaurants.
type MockRestaurantsMockRecorder struct {
	mock *MockRestaurants
}

// NewMockRestaurants creates a new mock instance.
func NewMockRestaurants(ctrl *gomock.Controller) *MockRestaurants {
	mock := &MockRestaurants{ctrl: ctrl}
	mock.recorder = &MockRestaurantsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurants) EXPECT() *MockRestaurantsMockRecorder {
	return m.recorder
}

// CreateAddresses mocks base method.
func (m *MockRestaurants) CreateAddresses(ctx context.Context, addresses entities.Addresses) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddresses", ctx, addresses)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddresses indicates an expected call of CreateAddresses.
func (mr *MockRestaurantsMockRecorder) CreateAddresses(ctx, addresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddresses", reflect.TypeOf((*MockRestaurants)(nil).CreateAddresses), ctx, addresses)
}

// CreateAvailables mocks base method.
func (m *MockRestaurants) CreateAvailables(ctx context.Context, availables entities.Availables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailables", ctx, availables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAvailables indicates an expected call of CreateAvailables.
func (mr *MockRestaurantsMockRecorder) CreateAvailables(ctx, availables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailables", reflect.TypeOf((*MockRestaurants)(nil).CreateAvailables), ctx, availables)
}

// CreateBranchCategoryRelations mocks base method.
func (m *MockRestaurants) CreateBranchCategoryRelations(ctx context.Context, branchCategoryRelations entities.BranchCategoryRelations) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranchCategoryRelations", ctx, branchCategoryRelations)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranchCategoryRelations indicates an expected call of CreateBranchCategoryRelations.
func (mr *MockRestaurantsMockRecorder) CreateBranchCategoryRelations(ctx, branchCategoryRelations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranchCategoryRelations", reflect.TypeOf((*MockRestaurants)(nil).CreateBranchCategoryRelations), ctx, branchCategoryRelations)
}

// CreateBranches mocks base method.
func (m *MockRestaurants) CreateBranches(ctx context.Context, branches entities.Branches) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranches", ctx, branches)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranches indicates an expected call of CreateBranches.
func (mr *MockRestaurantsMockRecorder) CreateBranches(ctx, branches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranches", reflect.TypeOf((*MockRestaurants)(nil).CreateBranches), ctx, branches)
}

// CreatePriceRanges mocks base method.
func (m *MockRestaurants) CreatePriceRanges(ctx context.Context, priceRanges entities.PriceRanges) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePriceRanges", ctx, priceRanges)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePriceRanges indicates an expected call of CreatePriceRanges.
func (mr *MockRestaurantsMockRecorder) CreatePriceRanges(ctx, priceRanges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePriceRanges", reflect.TypeOf((*MockRestaurants)(nil).CreatePriceRanges), ctx, priceRanges)
}

// CreateRestaurants mocks base method.
func (m *MockRestaurants) CreateRestaurants(ctx context.Context, restaurants entities.Restaurants) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurants", ctx, restaurants)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRestaurants indicates an expected call of CreateRestaurants.
func (mr *MockRestaurantsMockRecorder) CreateRestaurants(ctx, restaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurants", reflect.TypeOf((*MockRestaurants)(nil).CreateRestaurants), ctx, restaurants)
}

// CreateTables mocks base method.
func (m *MockRestaurants) CreateTables(ctx context.Context, tables entities.Tables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTables", ctx, tables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTables indicates an expected call of CreateTables.
func (mr *MockRestaurantsMockRecorder) CreateTables(ctx, tables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTables", reflect.TypeOf((*MockRestaurants)(nil).CreateTables), ctx, tables)
}

// DeleteAddresses mocks base method.
func (m *MockRestaurants) DeleteAddresses(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddresses", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddresses indicates an expected call of DeleteAddresses.
func (mr *MockRestaurantsMockRecorder) DeleteAddresses(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddresses", reflect.TypeOf((*MockRestaurants)(nil).DeleteAddresses), ctx, ids)
}

// DeleteAvailables mocks base method.
func (m *MockRestaurants) DeleteAvailables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvailables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvailables indicates an expected call of DeleteAvailables.
func (mr *MockRestaurantsMockRecorder) DeleteAvailables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvailables", reflect.TypeOf((*MockRestaurants)(nil).DeleteAvailables), ctx, ids)
}

// DeleteBranchCategoryRelations mocks base method.
func (m *MockRestaurants) DeleteBranchCategoryRelations(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranchCategoryRelations", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranchCategoryRelations indicates an expected call of DeleteBranchCategoryRelations.
func (mr *MockRestaurantsMockRecorder) DeleteBranchCategoryRelations(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranchCategoryRelations", reflect.TypeOf((*MockRestaurants)(nil).DeleteBranchCategoryRelations), ctx, ids)
}

// DeleteBranches mocks base method.
func (m *MockRestaurants) DeleteBranches(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranches", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranches indicates an expected call of DeleteBranches.
func (mr *MockRestaurantsMockRecorder) DeleteBranches(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranches", reflect.TypeOf((*MockRestaurants)(nil).DeleteBranches), ctx, ids)
}

// DeletePriceRanges mocks base method.
func (m *MockRestaurants) DeletePriceRanges(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePriceRanges", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePriceRanges indicates an expected call of DeletePriceRanges.
func (mr *MockRestaurantsMockRecorder) DeletePriceRanges(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePriceRanges", reflect.TypeOf((*MockRestaurants)(nil).DeletePriceRanges), ctx, ids)
}

// DeleteRestaurants mocks base method.
func (m *MockRestaurants) DeleteRestaurants(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurants", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurants indicates an expected call of DeleteRestaurants.
func (mr *MockRestaurantsMockRecorder) DeleteRestaurants(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurants", reflect.TypeOf((*MockRestaurants)(nil).DeleteRestaurants), ctx, ids)
}

// DeleteTables mocks base method.
func (m *MockRestaurants) DeleteTables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTables indicates an expected call of DeleteTables.
func (mr *MockRestaurantsMockRecorder) DeleteTables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTables", reflect.TypeOf((*MockRestaurants)(nil).DeleteTables), ctx, ids)
}

// ReadRestaurant mocks base method.
func (m *MockRestaurants) ReadRestaurant(ctx context.Context, id string) (*entities.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurant", ctx, id)
	ret0, _ := ret[0].(*entities.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurant indicates an expected call of ReadRestaurant.
func (mr *MockRestaurantsMockRecorder) ReadRestaurant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurant", reflect.TypeOf((*MockRestaurants)(nil).ReadRestaurant), ctx, id)
}

// ReadRestaurantFullInfo mocks base method.
func (m *MockRestaurants) ReadRestaurantFullInfo(ctx context.Context, id string) (*aggregates.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurantFullInfo", ctx, id)
	ret0, _ := ret[0].(*aggregates.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurantFullInfo indicates an expected call of ReadRestaurantFullInfo.
func (mr *MockRestaurantsMockRecorder) ReadRestaurantFullInfo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurantFullInfo", reflect.TypeOf((*MockRestaurants)(nil).ReadRestaurantFullInfo), ctx, id)
}

// UpdateAddress mocks base method.
func (m *MockRestaurants) UpdateAddress(ctx context.Context, updateAddress *entities.UpdateAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, updateAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockRestaurantsMockRecorder) UpdateAddress(ctx, updateAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockRestaurants)(nil).UpdateAddress), ctx, updateAddress)
}

// UpdateAvailable mocks base method.
func (m *MockRestaurants) UpdateAvailable(ctx context.Context, updateAvailable *entities.UpdateAvailable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvailable", ctx, updateAvailable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvailable indicates an expected call of UpdateAvailable.
func (mr *MockRestaurantsMockRecorder) UpdateAvailable(ctx, updateAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvailable", reflect.TypeOf((*MockRestaurants)(nil).UpdateAvailable), ctx, updateAvailable)
}

// UpdateBranch mocks base method.
func (m *MockRestaurants) UpdateBranch(ctx context.Context, updateBranch *entities.UpdateBranch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranch", ctx, updateBranch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranch indicates an expected call of UpdateBranch.
func (mr *MockRestaurantsMockRecorder) UpdateBranch(ctx, updateBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranch", reflect.TypeOf((*MockRestaurants)(nil).UpdateBranch), ctx, updateBranch)
}

// UpdateBranchCategoryRelation mocks base method.
func (m *MockRestaurants) UpdateBranchCategoryRelation(ctx context.Context, updateBranchCategoryRelation *entities.UpdateBranchCategoryRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranchCategoryRelation", ctx, updateBranchCategoryRelation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranchCategoryRelation indicates an expected call of UpdateBranchCategoryRelation.
func (mr *MockRestaurantsMockRecorder) UpdateBranchCategoryRelation(ctx, updateBranchCategoryRelation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranchCategoryRelation", reflect.TypeOf((*MockRestaurants)(nil).UpdateBranchCategoryRelation), ctx, updateBranchCategoryRelation)
}

// UpdatePriceRange mocks base method.
func (m *MockRestaurants) UpdatePriceRange(ctx context.Context, updatePriceRange *entities.UpdatePriceRange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePriceRange", ctx, updatePriceRange)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePriceRange indicates an expected call of UpdatePriceRange.
func (mr *MockRestaurantsMockRecorder) UpdatePriceRange(ctx, updatePriceRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePriceRange", reflect.TypeOf((*MockRestaurants)(nil).UpdatePriceRange), ctx, updatePriceRange)
}

// UpdateRestaurant mocks base method.
func (m *MockRestaurants) UpdateRestaurant(ctx context.Context, updateRestaurant *entities.UpdateRestaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurant", ctx, updateRestaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurant indicates an expected call of UpdateRestaurant.
func (mr *MockRestaurantsMockRecorder) UpdateRestaurant(ctx, updateRestaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurant", reflect.TypeOf((*MockRestaurants)(nil).UpdateRestaurant), ctx, updateRestaurant)
}

// UpdateTable mocks base method.
func (m *MockRestaurants) UpdateTable(ctx context.Context, updateTable *entities.UpdateTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTable", ctx, updateTable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockRestaurantsMockRecorder) UpdateTable(ctx, updateTable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockRestaurants)(nil).UpdateTable), ctx, updateTable)
}

// MockRestaurantsWithTransaction is a mock of RestaurantsWithTransaction interface.
type MockRestaurantsWithTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantsWithTransactionMockRecorder
	isgomock struct{}
}

// MockRestaurantsWithTransactionMockRecorder is the mock recorder for MockRestaurantsWithTransaction.
type MockRestaurantsWithTransactionMockRecorder struct {
	mock *MockRestaurantsWithTransaction
}

// NewMockRestaurantsWithTransaction creates a new mock instance.
func NewMockRestaurantsWithTransaction(ctrl *gomock.Controller) *MockRestaurantsWithTransaction {
	mock := &MockRestaurantsWithTransaction{ctrl: ctrl}
	mock.recorder = &MockRestaurantsWithTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurantsWithTransaction) EXPECT() *MockRestaurantsWithTransactionMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockRestaurantsWithTransaction) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockRestaurantsWithTransactionMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).Commit))
}

// CreateAddresses mocks base method.
func (m *MockRestaurantsWithTransaction) CreateAddresses(ctx context.Context, addresses entities.Addresses) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddresses", ctx, addresses)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddresses indicates an expected call of CreateAddresses.
func (mr *MockRestaurantsWithTransactionMockRecorder) CreateAddresses(ctx, addresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddresses", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).CreateAddresses), ctx, addresses)
}

// CreateAvailables mocks base method.
func (m *MockRestaurantsWithTransaction) CreateAvailables(ctx context.Context, availables entities.Availables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailables", ctx, availables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAvailables indicates an expected call of CreateAvailables.
func (mr *MockRestaurantsWithTransactionMockRecorder) CreateAvailables(ctx, availables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailables", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).CreateAvailables), ctx, availables)
}

// CreateBranchCategoryRelations mocks base method.
func (m *MockRestaurantsWithTransaction) CreateBranchCategoryRelations(ctx context.Context, branchCategoryRelations entities.BranchCategoryRelations) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranchCategoryRelations", ctx, branchCategoryRelations)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranchCategoryRelations indicates an expected call of CreateBranchCategoryRelations.
func (mr *MockRestaurantsWithTransactionMockRecorder) CreateBranchCategoryRelations(ctx, branchCategoryRelations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranchCategoryRelations", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).CreateBranchCategoryRelations), ctx, branchCategoryRelations)
}

// CreateBranches mocks base method.
func (m *MockRestaurantsWithTransaction) CreateBranches(ctx context.Context, branches entities.Branches) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranches", ctx, branches)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranches indicates an expected call of CreateBranches.
func (mr *MockRestaurantsWithTransactionMockRecorder) CreateBranches(ctx, branches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranches", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).CreateBranches), ctx, branches)
}

// CreatePriceRanges mocks base method.
func (m *MockRestaurantsWithTransaction) CreatePriceRanges(ctx context.Context, priceRanges entities.PriceRanges) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePriceRanges", ctx, priceRanges)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePriceRanges indicates an expected call of CreatePriceRanges.
func (mr *MockRestaurantsWithTransactionMockRecorder) CreatePriceRanges(ctx, priceRanges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePriceRanges", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).CreatePriceRanges), ctx, priceRanges)
}

// CreateRestaurants mocks base method.
func (m *MockRestaurantsWithTransaction) CreateRestaurants(ctx context.Context, restaurants entities.Restaurants) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurants", ctx, restaurants)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRestaurants indicates an expected call of CreateRestaurants.
func (mr *MockRestaurantsWithTransactionMockRecorder) CreateRestaurants(ctx, restaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurants", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).CreateRestaurants), ctx, restaurants)
}

// CreateTables mocks base method.
func (m *MockRestaurantsWithTransaction) CreateTables(ctx context.Context, tables entities.Tables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTables", ctx, tables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTables indicates an expected call of CreateTables.
func (mr *MockRestaurantsWithTransactionMockRecorder) CreateTables(ctx, tables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTables", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).CreateTables), ctx, tables)
}

// DeleteAddresses mocks base method.
func (m *MockRestaurantsWithTransaction) DeleteAddresses(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddresses", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddresses indicates an expected call of DeleteAddresses.
func (mr *MockRestaurantsWithTransactionMockRecorder) DeleteAddresses(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddresses", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).DeleteAddresses), ctx, ids)
}

// DeleteAvailables mocks base method.
func (m *MockRestaurantsWithTransaction) DeleteAvailables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvailables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvailables indicates an expected call of DeleteAvailables.
func (mr *MockRestaurantsWithTransactionMockRecorder) DeleteAvailables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvailables", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).DeleteAvailables), ctx, ids)
}

// DeleteBranchCategoryRelations mocks base method.
func (m *MockRestaurantsWithTransaction) DeleteBranchCategoryRelations(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranchCategoryRelations", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranchCategoryRelations indicates an expected call of DeleteBranchCategoryRelations.
func (mr *MockRestaurantsWithTransactionMockRecorder) DeleteBranchCategoryRelations(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranchCategoryRelations", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).DeleteBranchCategoryRelations), ctx, ids)
}

// DeleteBranches mocks base method.
func (m *MockRestaurantsWithTransaction) DeleteBranches(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranches", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranches indicates an expected call of DeleteBranches.
func (mr *MockRestaurantsWithTransactionMockRecorder) DeleteBranches(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranches", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).DeleteBranches), ctx, ids)
}

// DeletePriceRanges mocks base method.
func (m *MockRestaurantsWithTransaction) DeletePriceRanges(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePriceRanges", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePriceRanges indicates an expected call of DeletePriceRanges.
func (mr *MockRestaurantsWithTransactionMockRecorder) DeletePriceRanges(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePriceRanges", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).DeletePriceRanges), ctx, ids)
}

// DeleteRestaurants mocks base method.
func (m *MockRestaurantsWithTransaction) DeleteRestaurants(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurants", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurants indicates an expected call of DeleteRestaurants.
func (mr *MockRestaurantsWithTransactionMockRecorder) DeleteRestaurants(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurants", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).DeleteRestaurants), ctx, ids)
}

// DeleteTables mocks base method.
func (m *MockRestaurantsWithTransaction) DeleteTables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTables indicates an expected call of DeleteTables.
func (mr *MockRestaurantsWithTransactionMockRecorder) DeleteTables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTables", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).DeleteTables), ctx, ids)
}

// ReadRestaurant mocks base method.
func (m *MockRestaurantsWithTransaction) ReadRestaurant(ctx context.Context, id string) (*entities.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurant", ctx, id)
	ret0, _ := ret[0].(*entities.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurant indicates an expected call of ReadRestaurant.
func (mr *MockRestaurantsWithTransactionMockRecorder) ReadRestaurant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurant", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).ReadRestaurant), ctx, id)
}

// ReadRestaurantFullInfo mocks base method.
func (m *MockRestaurantsWithTransaction) ReadRestaurantFullInfo(ctx context.Context, id string) (*aggregates.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurantFullInfo", ctx, id)
	ret0, _ := ret[0].(*aggregates.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurantFullInfo indicates an expected call of ReadRestaurantFullInfo.
func (mr *MockRestaurantsWithTransactionMockRecorder) ReadRestaurantFullInfo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurantFullInfo", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).ReadRestaurantFullInfo), ctx, id)
}

// Rollback mocks base method.
func (m *MockRestaurantsWithTransaction) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockRestaurantsWithTransactionMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).Rollback))
}

// UpdateAddress mocks base method.
func (m *MockRestaurantsWithTransaction) UpdateAddress(ctx context.Context, updateAddress *entities.UpdateAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, updateAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockRestaurantsWithTransactionMockRecorder) UpdateAddress(ctx, updateAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).UpdateAddress), ctx, updateAddress)
}

// UpdateAvailable mocks base method.
func (m *MockRestaurantsWithTransaction) UpdateAvailable(ctx context.Context, updateAvailable *entities.UpdateAvailable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvailable", ctx, updateAvailable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvailable indicates an expected call of UpdateAvailable.
func (mr *MockRestaurantsWithTransactionMockRecorder) UpdateAvailable(ctx, updateAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvailable", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).UpdateAvailable), ctx, updateAvailable)
}

// UpdateBranch mocks base method.
func (m *MockRestaurantsWithTransaction) UpdateBranch(ctx context.Context, updateBranch *entities.UpdateBranch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranch", ctx, updateBranch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranch indicates an expected call of UpdateBranch.
func (mr *MockRestaurantsWithTransactionMockRecorder) UpdateBranch(ctx, updateBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranch", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).UpdateBranch), ctx, updateBranch)
}

// UpdateBranchCategoryRelation mocks base method.
func (m *MockRestaurantsWithTransaction) UpdateBranchCategoryRelation(ctx context.Context, updateBranchCategoryRelation *entities.UpdateBranchCategoryRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranchCategoryRelation", ctx, updateBranchCategoryRelation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranchCategoryRelation indicates an expected call of UpdateBranchCategoryRelation.
func (mr *MockRestaurantsWithTransactionMockRecorder) UpdateBranchCategoryRelation(ctx, updateBranchCategoryRelation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranchCategoryRelation", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).UpdateBranchCategoryRelation), ctx, updateBranchCategoryRelation)
}

// UpdatePriceRange mocks base method.
func (m *MockRestaurantsWithTransaction) UpdatePriceRange(ctx context.Context, updatePriceRange *entities.UpdatePriceRange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePriceRange", ctx, updatePriceRange)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePriceRange indicates an expected call of UpdatePriceRange.
func (mr *MockRestaurantsWithTransactionMockRecorder) UpdatePriceRange(ctx, updatePriceRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePriceRange", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).UpdatePriceRange), ctx, updatePriceRange)
}

// UpdateRestaurant mocks base method.
func (m *MockRestaurantsWithTransaction) UpdateRestaurant(ctx context.Context, updateRestaurant *entities.UpdateRestaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurant", ctx, updateRestaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurant indicates an expected call of UpdateRestaurant.
func (mr *MockRestaurantsWithTransactionMockRecorder) UpdateRestaurant(ctx, updateRestaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurant", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).UpdateRestaurant), ctx, updateRestaurant)
}

// UpdateTable mocks base method.
func (m *MockRestaurantsWithTransaction) UpdateTable(ctx context.Context, updateTable *entities.UpdateTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTable", ctx, updateTable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockRestaurantsWithTransactionMockRecorder) UpdateTable(ctx, updateTable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockRestaurantsWithTransaction)(nil).UpdateTable), ctx, updateTable)
}
