// Code generated by MockGen. DO NOT EDIT.
// Source: restaurants.go
//
// Generated by this command:
//
//	mockgen -source=restaurants.go -destination=./mocks/restaurants_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	aggregates "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/aggregates"
	dtos "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/dtos"
	entities "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchRestaurantsFullInfo is a mock of SearchRestaurantsFullInfo interface.
type MockSearchRestaurantsFullInfo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRestaurantsFullInfoMockRecorder
	isgomock struct{}
}

// MockSearchRestaurantsFullInfoMockRecorder is the mock recorder for MockSearchRestaurantsFullInfo.
type MockSearchRestaurantsFullInfoMockRecorder struct {
	mock *MockSearchRestaurantsFullInfo
}

// NewMockSearchRestaurantsFullInfo creates a new mock instance.
func NewMockSearchRestaurantsFullInfo(ctrl *gomock.Controller) *MockSearchRestaurantsFullInfo {
	mock := &MockSearchRestaurantsFullInfo{ctrl: ctrl}
	mock.recorder = &MockSearchRestaurantsFullInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRestaurantsFullInfo) EXPECT() *MockSearchRestaurantsFullInfoMockRecorder {
	return m.recorder
}

// SearchRestaurantsFullInfo mocks base method.
func (m *MockSearchRestaurantsFullInfo) SearchRestaurantsFullInfo(ctx context.Context, searchRestaurants dtos.SearchRestaurants) ([]aggregates.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRestaurantsFullInfo", ctx, searchRestaurants)
	ret0, _ := ret[0].([]aggregates.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRestaurantsFullInfo indicates an expected call of SearchRestaurantsFullInfo.
func (mr *MockSearchRestaurantsFullInfoMockRecorder) SearchRestaurantsFullInfo(ctx, searchRestaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRestaurantsFullInfo", reflect.TypeOf((*MockSearchRestaurantsFullInfo)(nil).SearchRestaurantsFullInfo), ctx, searchRestaurants)
}

// MockRestaurants is a mock of Restaurants interface.
type MockRestaurants struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantsMockRecorder
	isgomock struct{}
}

// MockRestaurantsMockRecorder is the mock recorder for MockRestaurants.
type MockRestaurantsMockRecorder struct {
	mock *MockRestaurants
}

// NewMockRestaurants creates a new mock instance.
func NewMockRestaurants(ctrl *gomock.Controller) *MockRestaurants {
	mock := &MockRestaurants{ctrl: ctrl}
	mock.recorder = &MockRestaurantsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurants) EXPECT() *MockRestaurantsMockRecorder {
	return m.recorder
}

// CreateRestaurants mocks base method.
func (m *MockRestaurants) CreateRestaurants(ctx context.Context, restaurants entities.Restaurants) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurants", ctx, restaurants)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRestaurants indicates an expected call of CreateRestaurants.
func (mr *MockRestaurantsMockRecorder) CreateRestaurants(ctx, restaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurants", reflect.TypeOf((*MockRestaurants)(nil).CreateRestaurants), ctx, restaurants)
}

// DeleteRestaurants mocks base method.
func (m *MockRestaurants) DeleteRestaurants(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurants", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurants indicates an expected call of DeleteRestaurants.
func (mr *MockRestaurantsMockRecorder) DeleteRestaurants(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurants", reflect.TypeOf((*MockRestaurants)(nil).DeleteRestaurants), ctx, ids)
}

// ReadRestaurantFullInfo mocks base method.
func (m *MockRestaurants) ReadRestaurantFullInfo(ctx context.Context, id string) (aggregates.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurantFullInfo", ctx, id)
	ret0, _ := ret[0].(aggregates.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurantFullInfo indicates an expected call of ReadRestaurantFullInfo.
func (mr *MockRestaurantsMockRecorder) ReadRestaurantFullInfo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurantFullInfo", reflect.TypeOf((*MockRestaurants)(nil).ReadRestaurantFullInfo), ctx, id)
}

// UpdateRestaurant mocks base method.
func (m *MockRestaurants) UpdateRestaurant(ctx context.Context, updateRestaurant entities.UpdateRestaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurant", ctx, updateRestaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurant indicates an expected call of UpdateRestaurant.
func (mr *MockRestaurantsMockRecorder) UpdateRestaurant(ctx, updateRestaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurant", reflect.TypeOf((*MockRestaurants)(nil).UpdateRestaurant), ctx, updateRestaurant)
}

// MockBranches is a mock of Branches interface.
type MockBranches struct {
	ctrl     *gomock.Controller
	recorder *MockBranchesMockRecorder
	isgomock struct{}
}

// MockBranchesMockRecorder is the mock recorder for MockBranches.
type MockBranchesMockRecorder struct {
	mock *MockBranches
}

// NewMockBranches creates a new mock instance.
func NewMockBranches(ctrl *gomock.Controller) *MockBranches {
	mock := &MockBranches{ctrl: ctrl}
	mock.recorder = &MockBranchesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBranches) EXPECT() *MockBranchesMockRecorder {
	return m.recorder
}

// CreateBranches mocks base method.
func (m *MockBranches) CreateBranches(ctx context.Context, branches entities.Branches) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranches", ctx, branches)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranches indicates an expected call of CreateBranches.
func (mr *MockBranchesMockRecorder) CreateBranches(ctx, branches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranches", reflect.TypeOf((*MockBranches)(nil).CreateBranches), ctx, branches)
}

// DeleteBranches mocks base method.
func (m *MockBranches) DeleteBranches(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranches", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranches indicates an expected call of DeleteBranches.
func (mr *MockBranchesMockRecorder) DeleteBranches(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranches", reflect.TypeOf((*MockBranches)(nil).DeleteBranches), ctx, ids)
}

// UpdateBranch mocks base method.
func (m *MockBranches) UpdateBranch(ctx context.Context, updateBranch entities.UpdateBranch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranch", ctx, updateBranch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranch indicates an expected call of UpdateBranch.
func (mr *MockBranchesMockRecorder) UpdateBranch(ctx, updateBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranch", reflect.TypeOf((*MockBranches)(nil).UpdateBranch), ctx, updateBranch)
}

// MockAddresses is a mock of Addresses interface.
type MockAddresses struct {
	ctrl     *gomock.Controller
	recorder *MockAddressesMockRecorder
	isgomock struct{}
}

// MockAddressesMockRecorder is the mock recorder for MockAddresses.
type MockAddressesMockRecorder struct {
	mock *MockAddresses
}

// NewMockAddresses creates a new mock instance.
func NewMockAddresses(ctrl *gomock.Controller) *MockAddresses {
	mock := &MockAddresses{ctrl: ctrl}
	mock.recorder = &MockAddressesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddresses) EXPECT() *MockAddressesMockRecorder {
	return m.recorder
}

// CreateAddresses mocks base method.
func (m *MockAddresses) CreateAddresses(ctx context.Context, addresses entities.Addresses) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddresses", ctx, addresses)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddresses indicates an expected call of CreateAddresses.
func (mr *MockAddressesMockRecorder) CreateAddresses(ctx, addresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddresses", reflect.TypeOf((*MockAddresses)(nil).CreateAddresses), ctx, addresses)
}

// DeleteAddresses mocks base method.
func (m *MockAddresses) DeleteAddresses(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddresses", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddresses indicates an expected call of DeleteAddresses.
func (mr *MockAddressesMockRecorder) DeleteAddresses(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddresses", reflect.TypeOf((*MockAddresses)(nil).DeleteAddresses), ctx, ids)
}

// UpdateAddress mocks base method.
func (m *MockAddresses) UpdateAddress(ctx context.Context, updateAddress entities.UpdateAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, updateAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockAddressesMockRecorder) UpdateAddress(ctx, updateAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockAddresses)(nil).UpdateAddress), ctx, updateAddress)
}

// MockPriceRanges is a mock of PriceRanges interface.
type MockPriceRanges struct {
	ctrl     *gomock.Controller
	recorder *MockPriceRangesMockRecorder
	isgomock struct{}
}

// MockPriceRangesMockRecorder is the mock recorder for MockPriceRanges.
type MockPriceRangesMockRecorder struct {
	mock *MockPriceRanges
}

// NewMockPriceRanges creates a new mock instance.
func NewMockPriceRanges(ctrl *gomock.Controller) *MockPriceRanges {
	mock := &MockPriceRanges{ctrl: ctrl}
	mock.recorder = &MockPriceRangesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceRanges) EXPECT() *MockPriceRangesMockRecorder {
	return m.recorder
}

// CreatePriceRanges mocks base method.
func (m *MockPriceRanges) CreatePriceRanges(ctx context.Context, priceRanges entities.PriceRanges) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePriceRanges", ctx, priceRanges)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePriceRanges indicates an expected call of CreatePriceRanges.
func (mr *MockPriceRangesMockRecorder) CreatePriceRanges(ctx, priceRanges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePriceRanges", reflect.TypeOf((*MockPriceRanges)(nil).CreatePriceRanges), ctx, priceRanges)
}

// DeletePriceRanges mocks base method.
func (m *MockPriceRanges) DeletePriceRanges(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePriceRanges", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePriceRanges indicates an expected call of DeletePriceRanges.
func (mr *MockPriceRangesMockRecorder) DeletePriceRanges(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePriceRanges", reflect.TypeOf((*MockPriceRanges)(nil).DeletePriceRanges), ctx, ids)
}

// UpdatePriceRange mocks base method.
func (m *MockPriceRanges) UpdatePriceRange(ctx context.Context, updatePriceRange entities.UpdatePriceRange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePriceRange", ctx, updatePriceRange)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePriceRange indicates an expected call of UpdatePriceRange.
func (mr *MockPriceRangesMockRecorder) UpdatePriceRange(ctx, updatePriceRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePriceRange", reflect.TypeOf((*MockPriceRanges)(nil).UpdatePriceRange), ctx, updatePriceRange)
}

// MockBranchCategoryRelations is a mock of BranchCategoryRelations interface.
type MockBranchCategoryRelations struct {
	ctrl     *gomock.Controller
	recorder *MockBranchCategoryRelationsMockRecorder
	isgomock struct{}
}

// MockBranchCategoryRelationsMockRecorder is the mock recorder for MockBranchCategoryRelations.
type MockBranchCategoryRelationsMockRecorder struct {
	mock *MockBranchCategoryRelations
}

// NewMockBranchCategoryRelations creates a new mock instance.
func NewMockBranchCategoryRelations(ctrl *gomock.Controller) *MockBranchCategoryRelations {
	mock := &MockBranchCategoryRelations{ctrl: ctrl}
	mock.recorder = &MockBranchCategoryRelationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBranchCategoryRelations) EXPECT() *MockBranchCategoryRelationsMockRecorder {
	return m.recorder
}

// CreateBranchCategoryRelations mocks base method.
func (m *MockBranchCategoryRelations) CreateBranchCategoryRelations(ctx context.Context, branchCategoryRelations entities.BranchCategoryRelations) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranchCategoryRelations", ctx, branchCategoryRelations)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranchCategoryRelations indicates an expected call of CreateBranchCategoryRelations.
func (mr *MockBranchCategoryRelationsMockRecorder) CreateBranchCategoryRelations(ctx, branchCategoryRelations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranchCategoryRelations", reflect.TypeOf((*MockBranchCategoryRelations)(nil).CreateBranchCategoryRelations), ctx, branchCategoryRelations)
}

// DeleteBranchCategoryRelations mocks base method.
func (m *MockBranchCategoryRelations) DeleteBranchCategoryRelations(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranchCategoryRelations", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranchCategoryRelations indicates an expected call of DeleteBranchCategoryRelations.
func (mr *MockBranchCategoryRelationsMockRecorder) DeleteBranchCategoryRelations(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranchCategoryRelations", reflect.TypeOf((*MockBranchCategoryRelations)(nil).DeleteBranchCategoryRelations), ctx, ids)
}

// UpdateBranchCategoryRelation mocks base method.
func (m *MockBranchCategoryRelations) UpdateBranchCategoryRelation(ctx context.Context, updateBranchCategoryRelation entities.UpdateBranchCategoryRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranchCategoryRelation", ctx, updateBranchCategoryRelation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranchCategoryRelation indicates an expected call of UpdateBranchCategoryRelation.
func (mr *MockBranchCategoryRelationsMockRecorder) UpdateBranchCategoryRelation(ctx, updateBranchCategoryRelation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranchCategoryRelation", reflect.TypeOf((*MockBranchCategoryRelations)(nil).UpdateBranchCategoryRelation), ctx, updateBranchCategoryRelation)
}

// MockTables is a mock of Tables interface.
type MockTables struct {
	ctrl     *gomock.Controller
	recorder *MockTablesMockRecorder
	isgomock struct{}
}

// MockTablesMockRecorder is the mock recorder for MockTables.
type MockTablesMockRecorder struct {
	mock *MockTables
}

// NewMockTables creates a new mock instance.
func NewMockTables(ctrl *gomock.Controller) *MockTables {
	mock := &MockTables{ctrl: ctrl}
	mock.recorder = &MockTablesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTables) EXPECT() *MockTablesMockRecorder {
	return m.recorder
}

// CreateTables mocks base method.
func (m *MockTables) CreateTables(ctx context.Context, tables entities.Tables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTables", ctx, tables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTables indicates an expected call of CreateTables.
func (mr *MockTablesMockRecorder) CreateTables(ctx, tables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTables", reflect.TypeOf((*MockTables)(nil).CreateTables), ctx, tables)
}

// DeleteTables mocks base method.
func (m *MockTables) DeleteTables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTables indicates an expected call of DeleteTables.
func (mr *MockTablesMockRecorder) DeleteTables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTables", reflect.TypeOf((*MockTables)(nil).DeleteTables), ctx, ids)
}

// UpdateTable mocks base method.
func (m *MockTables) UpdateTable(ctx context.Context, updateTable entities.UpdateTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTable", ctx, updateTable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockTablesMockRecorder) UpdateTable(ctx, updateTable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockTables)(nil).UpdateTable), ctx, updateTable)
}

// MockAvailables is a mock of Availables interface.
type MockAvailables struct {
	ctrl     *gomock.Controller
	recorder *MockAvailablesMockRecorder
	isgomock struct{}
}

// MockAvailablesMockRecorder is the mock recorder for MockAvailables.
type MockAvailablesMockRecorder struct {
	mock *MockAvailables
}

// NewMockAvailables creates a new mock instance.
func NewMockAvailables(ctrl *gomock.Controller) *MockAvailables {
	mock := &MockAvailables{ctrl: ctrl}
	mock.recorder = &MockAvailablesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvailables) EXPECT() *MockAvailablesMockRecorder {
	return m.recorder
}

// CreateAvailables mocks base method.
func (m *MockAvailables) CreateAvailables(ctx context.Context, availables entities.Availables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailables", ctx, availables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAvailables indicates an expected call of CreateAvailables.
func (mr *MockAvailablesMockRecorder) CreateAvailables(ctx, availables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailables", reflect.TypeOf((*MockAvailables)(nil).CreateAvailables), ctx, availables)
}

// DeleteAvailables mocks base method.
func (m *MockAvailables) DeleteAvailables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvailables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvailables indicates an expected call of DeleteAvailables.
func (mr *MockAvailablesMockRecorder) DeleteAvailables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvailables", reflect.TypeOf((*MockAvailables)(nil).DeleteAvailables), ctx, ids)
}

// UpdateAvailable mocks base method.
func (m *MockAvailables) UpdateAvailable(ctx context.Context, updateAvailable entities.UpdateAvailable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvailable", ctx, updateAvailable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvailable indicates an expected call of UpdateAvailable.
func (mr *MockAvailablesMockRecorder) UpdateAvailable(ctx, updateAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvailable", reflect.TypeOf((*MockAvailables)(nil).UpdateAvailable), ctx, updateAvailable)
}
