// Code generated by MockGen. DO NOT EDIT.
// Source: restaurants.go
//
// Generated by this command:
//
//	mockgen -source=restaurants.go -destination=./mocks/restaurants_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	aggregates "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/aggregates"
	dtos "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/dtos"
	entities "github.com/Leon180/go-event-driven-microservices/internal/services/restaurants/internal/restaurants/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchRestaurantsFullInfo is a mock of SearchRestaurantsFullInfo interface.
type MockSearchRestaurantsFullInfo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRestaurantsFullInfoMockRecorder
	isgomock struct{}
}

// MockSearchRestaurantsFullInfoMockRecorder is the mock recorder for MockSearchRestaurantsFullInfo.
type MockSearchRestaurantsFullInfoMockRecorder struct {
	mock *MockSearchRestaurantsFullInfo
}

// NewMockSearchRestaurantsFullInfo creates a new mock instance.
func NewMockSearchRestaurantsFullInfo(ctrl *gomock.Controller) *MockSearchRestaurantsFullInfo {
	mock := &MockSearchRestaurantsFullInfo{ctrl: ctrl}
	mock.recorder = &MockSearchRestaurantsFullInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRestaurantsFullInfo) EXPECT() *MockSearchRestaurantsFullInfoMockRecorder {
	return m.recorder
}

// SearchRestaurantsFullInfo mocks base method.
func (m *MockSearchRestaurantsFullInfo) SearchRestaurantsFullInfo(ctx context.Context, searchRestaurants *dtos.SearchRestaurants) (aggregates.Restaurants, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRestaurantsFullInfo", ctx, searchRestaurants)
	ret0, _ := ret[0].(aggregates.Restaurants)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRestaurantsFullInfo indicates an expected call of SearchRestaurantsFullInfo.
func (mr *MockSearchRestaurantsFullInfoMockRecorder) SearchRestaurantsFullInfo(ctx, searchRestaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRestaurantsFullInfo", reflect.TypeOf((*MockSearchRestaurantsFullInfo)(nil).SearchRestaurantsFullInfo), ctx, searchRestaurants)
}

// MockReadRestaurants is a mock of ReadRestaurants interface.
type MockReadRestaurants struct {
	ctrl     *gomock.Controller
	recorder *MockReadRestaurantsMockRecorder
	isgomock struct{}
}

// MockReadRestaurantsMockRecorder is the mock recorder for MockReadRestaurants.
type MockReadRestaurantsMockRecorder struct {
	mock *MockReadRestaurants
}

// NewMockReadRestaurants creates a new mock instance.
func NewMockReadRestaurants(ctrl *gomock.Controller) *MockReadRestaurants {
	mock := &MockReadRestaurants{ctrl: ctrl}
	mock.recorder = &MockReadRestaurantsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadRestaurants) EXPECT() *MockReadRestaurantsMockRecorder {
	return m.recorder
}

// ReadRestaurant mocks base method.
func (m *MockReadRestaurants) ReadRestaurant(ctx context.Context, id string) (*entities.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurant", ctx, id)
	ret0, _ := ret[0].(*entities.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurant indicates an expected call of ReadRestaurant.
func (mr *MockReadRestaurantsMockRecorder) ReadRestaurant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurant", reflect.TypeOf((*MockReadRestaurants)(nil).ReadRestaurant), ctx, id)
}

// ReadRestaurantFullInfo mocks base method.
func (m *MockReadRestaurants) ReadRestaurantFullInfo(ctx context.Context, id string) (*aggregates.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurantFullInfo", ctx, id)
	ret0, _ := ret[0].(*aggregates.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurantFullInfo indicates an expected call of ReadRestaurantFullInfo.
func (mr *MockReadRestaurantsMockRecorder) ReadRestaurantFullInfo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurantFullInfo", reflect.TypeOf((*MockReadRestaurants)(nil).ReadRestaurantFullInfo), ctx, id)
}

// MockUpdateRestaurants is a mock of UpdateRestaurants interface.
type MockUpdateRestaurants struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateRestaurantsMockRecorder
	isgomock struct{}
}

// MockUpdateRestaurantsMockRecorder is the mock recorder for MockUpdateRestaurants.
type MockUpdateRestaurantsMockRecorder struct {
	mock *MockUpdateRestaurants
}

// NewMockUpdateRestaurants creates a new mock instance.
func NewMockUpdateRestaurants(ctrl *gomock.Controller) *MockUpdateRestaurants {
	mock := &MockUpdateRestaurants{ctrl: ctrl}
	mock.recorder = &MockUpdateRestaurantsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateRestaurants) EXPECT() *MockUpdateRestaurantsMockRecorder {
	return m.recorder
}

// CreateAddresses mocks base method.
func (m *MockUpdateRestaurants) CreateAddresses(ctx context.Context, addresses entities.Addresses) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddresses", ctx, addresses)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddresses indicates an expected call of CreateAddresses.
func (mr *MockUpdateRestaurantsMockRecorder) CreateAddresses(ctx, addresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddresses", reflect.TypeOf((*MockUpdateRestaurants)(nil).CreateAddresses), ctx, addresses)
}

// CreateAvailables mocks base method.
func (m *MockUpdateRestaurants) CreateAvailables(ctx context.Context, availables entities.Availables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailables", ctx, availables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAvailables indicates an expected call of CreateAvailables.
func (mr *MockUpdateRestaurantsMockRecorder) CreateAvailables(ctx, availables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailables", reflect.TypeOf((*MockUpdateRestaurants)(nil).CreateAvailables), ctx, availables)
}

// CreateBranchCategoryRelations mocks base method.
func (m *MockUpdateRestaurants) CreateBranchCategoryRelations(ctx context.Context, branchCategoryRelations entities.BranchCategoryRelations) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranchCategoryRelations", ctx, branchCategoryRelations)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranchCategoryRelations indicates an expected call of CreateBranchCategoryRelations.
func (mr *MockUpdateRestaurantsMockRecorder) CreateBranchCategoryRelations(ctx, branchCategoryRelations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranchCategoryRelations", reflect.TypeOf((*MockUpdateRestaurants)(nil).CreateBranchCategoryRelations), ctx, branchCategoryRelations)
}

// CreateBranches mocks base method.
func (m *MockUpdateRestaurants) CreateBranches(ctx context.Context, branches entities.Branches) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranches", ctx, branches)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranches indicates an expected call of CreateBranches.
func (mr *MockUpdateRestaurantsMockRecorder) CreateBranches(ctx, branches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranches", reflect.TypeOf((*MockUpdateRestaurants)(nil).CreateBranches), ctx, branches)
}

// CreatePriceRanges mocks base method.
func (m *MockUpdateRestaurants) CreatePriceRanges(ctx context.Context, priceRanges entities.PriceRanges) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePriceRanges", ctx, priceRanges)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePriceRanges indicates an expected call of CreatePriceRanges.
func (mr *MockUpdateRestaurantsMockRecorder) CreatePriceRanges(ctx, priceRanges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePriceRanges", reflect.TypeOf((*MockUpdateRestaurants)(nil).CreatePriceRanges), ctx, priceRanges)
}

// CreateRestaurants mocks base method.
func (m *MockUpdateRestaurants) CreateRestaurants(ctx context.Context, restaurants entities.Restaurants) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurants", ctx, restaurants)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRestaurants indicates an expected call of CreateRestaurants.
func (mr *MockUpdateRestaurantsMockRecorder) CreateRestaurants(ctx, restaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurants", reflect.TypeOf((*MockUpdateRestaurants)(nil).CreateRestaurants), ctx, restaurants)
}

// CreateTables mocks base method.
func (m *MockUpdateRestaurants) CreateTables(ctx context.Context, tables entities.Tables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTables", ctx, tables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTables indicates an expected call of CreateTables.
func (mr *MockUpdateRestaurantsMockRecorder) CreateTables(ctx, tables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTables", reflect.TypeOf((*MockUpdateRestaurants)(nil).CreateTables), ctx, tables)
}

// DeleteAddresses mocks base method.
func (m *MockUpdateRestaurants) DeleteAddresses(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddresses", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddresses indicates an expected call of DeleteAddresses.
func (mr *MockUpdateRestaurantsMockRecorder) DeleteAddresses(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddresses", reflect.TypeOf((*MockUpdateRestaurants)(nil).DeleteAddresses), ctx, ids)
}

// DeleteAvailables mocks base method.
func (m *MockUpdateRestaurants) DeleteAvailables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvailables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvailables indicates an expected call of DeleteAvailables.
func (mr *MockUpdateRestaurantsMockRecorder) DeleteAvailables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvailables", reflect.TypeOf((*MockUpdateRestaurants)(nil).DeleteAvailables), ctx, ids)
}

// DeleteBranchCategoryRelations mocks base method.
func (m *MockUpdateRestaurants) DeleteBranchCategoryRelations(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranchCategoryRelations", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranchCategoryRelations indicates an expected call of DeleteBranchCategoryRelations.
func (mr *MockUpdateRestaurantsMockRecorder) DeleteBranchCategoryRelations(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranchCategoryRelations", reflect.TypeOf((*MockUpdateRestaurants)(nil).DeleteBranchCategoryRelations), ctx, ids)
}

// DeleteBranches mocks base method.
func (m *MockUpdateRestaurants) DeleteBranches(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranches", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranches indicates an expected call of DeleteBranches.
func (mr *MockUpdateRestaurantsMockRecorder) DeleteBranches(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranches", reflect.TypeOf((*MockUpdateRestaurants)(nil).DeleteBranches), ctx, ids)
}

// DeletePriceRanges mocks base method.
func (m *MockUpdateRestaurants) DeletePriceRanges(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePriceRanges", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePriceRanges indicates an expected call of DeletePriceRanges.
func (mr *MockUpdateRestaurantsMockRecorder) DeletePriceRanges(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePriceRanges", reflect.TypeOf((*MockUpdateRestaurants)(nil).DeletePriceRanges), ctx, ids)
}

// DeleteRestaurants mocks base method.
func (m *MockUpdateRestaurants) DeleteRestaurants(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurants", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurants indicates an expected call of DeleteRestaurants.
func (mr *MockUpdateRestaurantsMockRecorder) DeleteRestaurants(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurants", reflect.TypeOf((*MockUpdateRestaurants)(nil).DeleteRestaurants), ctx, ids)
}

// DeleteTables mocks base method.
func (m *MockUpdateRestaurants) DeleteTables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTables indicates an expected call of DeleteTables.
func (mr *MockUpdateRestaurantsMockRecorder) DeleteTables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTables", reflect.TypeOf((*MockUpdateRestaurants)(nil).DeleteTables), ctx, ids)
}

// UpdateAddress mocks base method.
func (m *MockUpdateRestaurants) UpdateAddress(ctx context.Context, updateAddress *entities.UpdateAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, updateAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockUpdateRestaurantsMockRecorder) UpdateAddress(ctx, updateAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockUpdateRestaurants)(nil).UpdateAddress), ctx, updateAddress)
}

// UpdateAvailable mocks base method.
func (m *MockUpdateRestaurants) UpdateAvailable(ctx context.Context, updateAvailable *entities.UpdateAvailable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvailable", ctx, updateAvailable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvailable indicates an expected call of UpdateAvailable.
func (mr *MockUpdateRestaurantsMockRecorder) UpdateAvailable(ctx, updateAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvailable", reflect.TypeOf((*MockUpdateRestaurants)(nil).UpdateAvailable), ctx, updateAvailable)
}

// UpdateBranch mocks base method.
func (m *MockUpdateRestaurants) UpdateBranch(ctx context.Context, updateBranch *entities.UpdateBranch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranch", ctx, updateBranch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranch indicates an expected call of UpdateBranch.
func (mr *MockUpdateRestaurantsMockRecorder) UpdateBranch(ctx, updateBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranch", reflect.TypeOf((*MockUpdateRestaurants)(nil).UpdateBranch), ctx, updateBranch)
}

// UpdateBranchCategoryRelation mocks base method.
func (m *MockUpdateRestaurants) UpdateBranchCategoryRelation(ctx context.Context, updateBranchCategoryRelation *entities.UpdateBranchCategoryRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranchCategoryRelation", ctx, updateBranchCategoryRelation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranchCategoryRelation indicates an expected call of UpdateBranchCategoryRelation.
func (mr *MockUpdateRestaurantsMockRecorder) UpdateBranchCategoryRelation(ctx, updateBranchCategoryRelation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranchCategoryRelation", reflect.TypeOf((*MockUpdateRestaurants)(nil).UpdateBranchCategoryRelation), ctx, updateBranchCategoryRelation)
}

// UpdatePriceRange mocks base method.
func (m *MockUpdateRestaurants) UpdatePriceRange(ctx context.Context, updatePriceRange *entities.UpdatePriceRange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePriceRange", ctx, updatePriceRange)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePriceRange indicates an expected call of UpdatePriceRange.
func (mr *MockUpdateRestaurantsMockRecorder) UpdatePriceRange(ctx, updatePriceRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePriceRange", reflect.TypeOf((*MockUpdateRestaurants)(nil).UpdatePriceRange), ctx, updatePriceRange)
}

// UpdateRestaurant mocks base method.
func (m *MockUpdateRestaurants) UpdateRestaurant(ctx context.Context, updateRestaurant *entities.UpdateRestaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurant", ctx, updateRestaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurant indicates an expected call of UpdateRestaurant.
func (mr *MockUpdateRestaurantsMockRecorder) UpdateRestaurant(ctx, updateRestaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurant", reflect.TypeOf((*MockUpdateRestaurants)(nil).UpdateRestaurant), ctx, updateRestaurant)
}

// UpdateTable mocks base method.
func (m *MockUpdateRestaurants) UpdateTable(ctx context.Context, updateTable *entities.UpdateTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTable", ctx, updateTable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockUpdateRestaurantsMockRecorder) UpdateTable(ctx, updateTable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockUpdateRestaurants)(nil).UpdateTable), ctx, updateTable)
}

// MockUpdateRestaurantsWithTransaction is a mock of UpdateRestaurantsWithTransaction interface.
type MockUpdateRestaurantsWithTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateRestaurantsWithTransactionMockRecorder
	isgomock struct{}
}

// MockUpdateRestaurantsWithTransactionMockRecorder is the mock recorder for MockUpdateRestaurantsWithTransaction.
type MockUpdateRestaurantsWithTransactionMockRecorder struct {
	mock *MockUpdateRestaurantsWithTransaction
}

// NewMockUpdateRestaurantsWithTransaction creates a new mock instance.
func NewMockUpdateRestaurantsWithTransaction(ctrl *gomock.Controller) *MockUpdateRestaurantsWithTransaction {
	mock := &MockUpdateRestaurantsWithTransaction{ctrl: ctrl}
	mock.recorder = &MockUpdateRestaurantsWithTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateRestaurantsWithTransaction) EXPECT() *MockUpdateRestaurantsWithTransactionMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).Commit))
}

// CreateAddresses mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) CreateAddresses(ctx context.Context, addresses entities.Addresses) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddresses", ctx, addresses)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddresses indicates an expected call of CreateAddresses.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) CreateAddresses(ctx, addresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddresses", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).CreateAddresses), ctx, addresses)
}

// CreateAvailables mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) CreateAvailables(ctx context.Context, availables entities.Availables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailables", ctx, availables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAvailables indicates an expected call of CreateAvailables.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) CreateAvailables(ctx, availables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailables", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).CreateAvailables), ctx, availables)
}

// CreateBranchCategoryRelations mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) CreateBranchCategoryRelations(ctx context.Context, branchCategoryRelations entities.BranchCategoryRelations) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranchCategoryRelations", ctx, branchCategoryRelations)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranchCategoryRelations indicates an expected call of CreateBranchCategoryRelations.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) CreateBranchCategoryRelations(ctx, branchCategoryRelations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranchCategoryRelations", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).CreateBranchCategoryRelations), ctx, branchCategoryRelations)
}

// CreateBranches mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) CreateBranches(ctx context.Context, branches entities.Branches) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranches", ctx, branches)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranches indicates an expected call of CreateBranches.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) CreateBranches(ctx, branches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranches", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).CreateBranches), ctx, branches)
}

// CreatePriceRanges mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) CreatePriceRanges(ctx context.Context, priceRanges entities.PriceRanges) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePriceRanges", ctx, priceRanges)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePriceRanges indicates an expected call of CreatePriceRanges.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) CreatePriceRanges(ctx, priceRanges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePriceRanges", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).CreatePriceRanges), ctx, priceRanges)
}

// CreateRestaurants mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) CreateRestaurants(ctx context.Context, restaurants entities.Restaurants) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurants", ctx, restaurants)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRestaurants indicates an expected call of CreateRestaurants.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) CreateRestaurants(ctx, restaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurants", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).CreateRestaurants), ctx, restaurants)
}

// CreateTables mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) CreateTables(ctx context.Context, tables entities.Tables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTables", ctx, tables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTables indicates an expected call of CreateTables.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) CreateTables(ctx, tables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTables", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).CreateTables), ctx, tables)
}

// DeleteAddresses mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) DeleteAddresses(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddresses", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddresses indicates an expected call of DeleteAddresses.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) DeleteAddresses(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddresses", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).DeleteAddresses), ctx, ids)
}

// DeleteAvailables mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) DeleteAvailables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvailables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvailables indicates an expected call of DeleteAvailables.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) DeleteAvailables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvailables", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).DeleteAvailables), ctx, ids)
}

// DeleteBranchCategoryRelations mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) DeleteBranchCategoryRelations(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranchCategoryRelations", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranchCategoryRelations indicates an expected call of DeleteBranchCategoryRelations.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) DeleteBranchCategoryRelations(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranchCategoryRelations", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).DeleteBranchCategoryRelations), ctx, ids)
}

// DeleteBranches mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) DeleteBranches(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranches", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranches indicates an expected call of DeleteBranches.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) DeleteBranches(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranches", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).DeleteBranches), ctx, ids)
}

// DeletePriceRanges mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) DeletePriceRanges(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePriceRanges", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePriceRanges indicates an expected call of DeletePriceRanges.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) DeletePriceRanges(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePriceRanges", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).DeletePriceRanges), ctx, ids)
}

// DeleteRestaurants mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) DeleteRestaurants(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurants", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurants indicates an expected call of DeleteRestaurants.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) DeleteRestaurants(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurants", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).DeleteRestaurants), ctx, ids)
}

// DeleteTables mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) DeleteTables(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTables", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTables indicates an expected call of DeleteTables.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) DeleteTables(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTables", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).DeleteTables), ctx, ids)
}

// Rollback mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).Rollback))
}

// UpdateAddress mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) UpdateAddress(ctx context.Context, updateAddress *entities.UpdateAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, updateAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) UpdateAddress(ctx, updateAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).UpdateAddress), ctx, updateAddress)
}

// UpdateAvailable mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) UpdateAvailable(ctx context.Context, updateAvailable *entities.UpdateAvailable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvailable", ctx, updateAvailable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvailable indicates an expected call of UpdateAvailable.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) UpdateAvailable(ctx, updateAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvailable", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).UpdateAvailable), ctx, updateAvailable)
}

// UpdateBranch mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) UpdateBranch(ctx context.Context, updateBranch *entities.UpdateBranch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranch", ctx, updateBranch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranch indicates an expected call of UpdateBranch.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) UpdateBranch(ctx, updateBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranch", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).UpdateBranch), ctx, updateBranch)
}

// UpdateBranchCategoryRelation mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) UpdateBranchCategoryRelation(ctx context.Context, updateBranchCategoryRelation *entities.UpdateBranchCategoryRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranchCategoryRelation", ctx, updateBranchCategoryRelation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranchCategoryRelation indicates an expected call of UpdateBranchCategoryRelation.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) UpdateBranchCategoryRelation(ctx, updateBranchCategoryRelation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranchCategoryRelation", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).UpdateBranchCategoryRelation), ctx, updateBranchCategoryRelation)
}

// UpdatePriceRange mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) UpdatePriceRange(ctx context.Context, updatePriceRange *entities.UpdatePriceRange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePriceRange", ctx, updatePriceRange)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePriceRange indicates an expected call of UpdatePriceRange.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) UpdatePriceRange(ctx, updatePriceRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePriceRange", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).UpdatePriceRange), ctx, updatePriceRange)
}

// UpdateRestaurant mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) UpdateRestaurant(ctx context.Context, updateRestaurant *entities.UpdateRestaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurant", ctx, updateRestaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurant indicates an expected call of UpdateRestaurant.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) UpdateRestaurant(ctx, updateRestaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurant", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).UpdateRestaurant), ctx, updateRestaurant)
}

// UpdateTable mocks base method.
func (m *MockUpdateRestaurantsWithTransaction) UpdateTable(ctx context.Context, updateTable *entities.UpdateTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTable", ctx, updateTable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockUpdateRestaurantsWithTransactionMockRecorder) UpdateTable(ctx, updateTable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockUpdateRestaurantsWithTransaction)(nil).UpdateTable), ctx, updateTable)
}
