// Code generated by MockGen. DO NOT EDIT.
// Source: books.go
//
// Generated by this command:
//
//	mockgen -source=books.go -destination=./mocks/books_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	aggregates "github.com/Leon180/go-event-driven-microservices/internal/services/read_restaurants/internal/restaurants/aggregates"
	dtos "github.com/Leon180/go-event-driven-microservices/internal/services/read_restaurants/internal/restaurants/dtos"
	entities "github.com/Leon180/go-event-driven-microservices/internal/services/read_restaurants/internal/restaurants/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchBooksFullInfo is a mock of SearchBooksFullInfo interface.
type MockSearchBooksFullInfo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchBooksFullInfoMockRecorder
	isgomock struct{}
}

// MockSearchBooksFullInfoMockRecorder is the mock recorder for MockSearchBooksFullInfo.
type MockSearchBooksFullInfoMockRecorder struct {
	mock *MockSearchBooksFullInfo
}

// NewMockSearchBooksFullInfo creates a new mock instance.
func NewMockSearchBooksFullInfo(ctrl *gomock.Controller) *MockSearchBooksFullInfo {
	mock := &MockSearchBooksFullInfo{ctrl: ctrl}
	mock.recorder = &MockSearchBooksFullInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchBooksFullInfo) EXPECT() *MockSearchBooksFullInfoMockRecorder {
	return m.recorder
}

// SearchBooksFullInfo mocks base method.
func (m *MockSearchBooksFullInfo) SearchBooksFullInfo(ctx context.Context, searchBooks *dtos.SearchBooks) (aggregates.Books, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchBooksFullInfo", ctx, searchBooks)
	ret0, _ := ret[0].(aggregates.Books)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchBooksFullInfo indicates an expected call of SearchBooksFullInfo.
func (mr *MockSearchBooksFullInfoMockRecorder) SearchBooksFullInfo(ctx, searchBooks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchBooksFullInfo", reflect.TypeOf((*MockSearchBooksFullInfo)(nil).SearchBooksFullInfo), ctx, searchBooks)
}

// MockReadBooks is a mock of ReadBooks interface.
type MockReadBooks struct {
	ctrl     *gomock.Controller
	recorder *MockReadBooksMockRecorder
	isgomock struct{}
}

// MockReadBooksMockRecorder is the mock recorder for MockReadBooks.
type MockReadBooksMockRecorder struct {
	mock *MockReadBooks
}

// NewMockReadBooks creates a new mock instance.
func NewMockReadBooks(ctrl *gomock.Controller) *MockReadBooks {
	mock := &MockReadBooks{ctrl: ctrl}
	mock.recorder = &MockReadBooksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadBooks) EXPECT() *MockReadBooksMockRecorder {
	return m.recorder
}

// ReadBook mocks base method.
func (m *MockReadBooks) ReadBook(ctx context.Context, id string) (*entities.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBook", ctx, id)
	ret0, _ := ret[0].(*entities.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBook indicates an expected call of ReadBook.
func (mr *MockReadBooksMockRecorder) ReadBook(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBook", reflect.TypeOf((*MockReadBooks)(nil).ReadBook), ctx, id)
}

// ReadBookFullInfo mocks base method.
func (m *MockReadBooks) ReadBookFullInfo(ctx context.Context, id string) (*aggregates.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBookFullInfo", ctx, id)
	ret0, _ := ret[0].(*aggregates.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBookFullInfo indicates an expected call of ReadBookFullInfo.
func (mr *MockReadBooksMockRecorder) ReadBookFullInfo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBookFullInfo", reflect.TypeOf((*MockReadBooks)(nil).ReadBookFullInfo), ctx, id)
}

// MockUpdateBooks is a mock of UpdateBooks interface.
type MockUpdateBooks struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateBooksMockRecorder
	isgomock struct{}
}

// MockUpdateBooksMockRecorder is the mock recorder for MockUpdateBooks.
type MockUpdateBooksMockRecorder struct {
	mock *MockUpdateBooks
}

// NewMockUpdateBooks creates a new mock instance.
func NewMockUpdateBooks(ctrl *gomock.Controller) *MockUpdateBooks {
	mock := &MockUpdateBooks{ctrl: ctrl}
	mock.recorder = &MockUpdateBooksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateBooks) EXPECT() *MockUpdateBooksMockRecorder {
	return m.recorder
}

// CreateBooks mocks base method.
func (m *MockUpdateBooks) CreateBooks(ctx context.Context, books entities.Books) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooks", ctx, books)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooks indicates an expected call of CreateBooks.
func (mr *MockUpdateBooksMockRecorder) CreateBooks(ctx, books any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooks", reflect.TypeOf((*MockUpdateBooks)(nil).CreateBooks), ctx, books)
}

// DeleteBooks mocks base method.
func (m *MockUpdateBooks) DeleteBooks(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooks", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooks indicates an expected call of DeleteBooks.
func (mr *MockUpdateBooksMockRecorder) DeleteBooks(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooks", reflect.TypeOf((*MockUpdateBooks)(nil).DeleteBooks), ctx, ids)
}

// UpdateBook mocks base method.
func (m *MockUpdateBooks) UpdateBook(ctx context.Context, updateBook *entities.UpdateBook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", ctx, updateBook)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockUpdateBooksMockRecorder) UpdateBook(ctx, updateBook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockUpdateBooks)(nil).UpdateBook), ctx, updateBook)
}

// MockUpdateBooksWithTransaction is a mock of UpdateBooksWithTransaction interface.
type MockUpdateBooksWithTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateBooksWithTransactionMockRecorder
	isgomock struct{}
}

// MockUpdateBooksWithTransactionMockRecorder is the mock recorder for MockUpdateBooksWithTransaction.
type MockUpdateBooksWithTransactionMockRecorder struct {
	mock *MockUpdateBooksWithTransaction
}

// NewMockUpdateBooksWithTransaction creates a new mock instance.
func NewMockUpdateBooksWithTransaction(ctrl *gomock.Controller) *MockUpdateBooksWithTransaction {
	mock := &MockUpdateBooksWithTransaction{ctrl: ctrl}
	mock.recorder = &MockUpdateBooksWithTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateBooksWithTransaction) EXPECT() *MockUpdateBooksWithTransactionMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockUpdateBooksWithTransaction) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockUpdateBooksWithTransactionMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockUpdateBooksWithTransaction)(nil).Commit))
}

// CreateBooks mocks base method.
func (m *MockUpdateBooksWithTransaction) CreateBooks(ctx context.Context, books entities.Books) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooks", ctx, books)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooks indicates an expected call of CreateBooks.
func (mr *MockUpdateBooksWithTransactionMockRecorder) CreateBooks(ctx, books any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooks", reflect.TypeOf((*MockUpdateBooksWithTransaction)(nil).CreateBooks), ctx, books)
}

// DeleteBooks mocks base method.
func (m *MockUpdateBooksWithTransaction) DeleteBooks(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooks", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooks indicates an expected call of DeleteBooks.
func (mr *MockUpdateBooksWithTransactionMockRecorder) DeleteBooks(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooks", reflect.TypeOf((*MockUpdateBooksWithTransaction)(nil).DeleteBooks), ctx, ids)
}

// Rollback mocks base method.
func (m *MockUpdateBooksWithTransaction) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockUpdateBooksWithTransactionMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockUpdateBooksWithTransaction)(nil).Rollback))
}

// UpdateBook mocks base method.
func (m *MockUpdateBooksWithTransaction) UpdateBook(ctx context.Context, updateBook *entities.UpdateBook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", ctx, updateBook)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockUpdateBooksWithTransactionMockRecorder) UpdateBook(ctx, updateBook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockUpdateBooksWithTransaction)(nil).UpdateBook), ctx, updateBook)
}
