// Code generated by MockGen. DO NOT EDIT.
// Source: books_redis.go
//
// Generated by this command:
//
//	mockgen -source=books_redis.go -destination=./mocks/books_redis_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	aggregates "github.com/Leon180/go-event-driven-microservices/internal/services/read_restaurants/internal/restaurants/aggregates"
	gomock "go.uber.org/mock/gomock"
)

// MockReadBooksRedis is a mock of ReadBooksRedis interface.
type MockReadBooksRedis struct {
	ctrl     *gomock.Controller
	recorder *MockReadBooksRedisMockRecorder
	isgomock struct{}
}

// MockReadBooksRedisMockRecorder is the mock recorder for MockReadBooksRedis.
type MockReadBooksRedisMockRecorder struct {
	mock *MockReadBooksRedis
}

// NewMockReadBooksRedis creates a new mock instance.
func NewMockReadBooksRedis(ctrl *gomock.Controller) *MockReadBooksRedis {
	mock := &MockReadBooksRedis{ctrl: ctrl}
	mock.recorder = &MockReadBooksRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadBooksRedis) EXPECT() *MockReadBooksRedisMockRecorder {
	return m.recorder
}

// ReadBook mocks base method.
func (m *MockReadBooksRedis) ReadBook(ctx context.Context, id string) (*aggregates.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBook", ctx, id)
	ret0, _ := ret[0].(*aggregates.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBook indicates an expected call of ReadBook.
func (mr *MockReadBooksRedisMockRecorder) ReadBook(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBook", reflect.TypeOf((*MockReadBooksRedis)(nil).ReadBook), ctx, id)
}

// MockSetBookRedis is a mock of SetBookRedis interface.
type MockSetBookRedis struct {
	ctrl     *gomock.Controller
	recorder *MockSetBookRedisMockRecorder
	isgomock struct{}
}

// MockSetBookRedisMockRecorder is the mock recorder for MockSetBookRedis.
type MockSetBookRedisMockRecorder struct {
	mock *MockSetBookRedis
}

// NewMockSetBookRedis creates a new mock instance.
func NewMockSetBookRedis(ctrl *gomock.Controller) *MockSetBookRedis {
	mock := &MockSetBookRedis{ctrl: ctrl}
	mock.recorder = &MockSetBookRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetBookRedis) EXPECT() *MockSetBookRedisMockRecorder {
	return m.recorder
}

// DeleteBook mocks base method.
func (m *MockSetBookRedis) DeleteBook(ctx context.Context, book *aggregates.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", ctx, book)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockSetBookRedisMockRecorder) DeleteBook(ctx, book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockSetBookRedis)(nil).DeleteBook), ctx, book)
}

// SetBook mocks base method.
func (m *MockSetBookRedis) SetBook(ctx context.Context, book *aggregates.Book, timeOut time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBook", ctx, book, timeOut)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBook indicates an expected call of SetBook.
func (mr *MockSetBookRedisMockRecorder) SetBook(ctx, book, timeOut any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBook", reflect.TypeOf((*MockSetBookRedis)(nil).SetBook), ctx, book, timeOut)
}
