// Code generated by MockGen. DO NOT EDIT.
// Source: restaurants_redis.go
//
// Generated by this command:
//
//	mockgen -source=restaurants_redis.go -destination=./mocks/restaurants_redis_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	aggregates "github.com/Leon180/go-event-driven-microservices/internal/services/read_restaurants/internal/restaurants/aggregates"
	gomock "go.uber.org/mock/gomock"
)

// MockReadRestaurantsRedis is a mock of ReadRestaurantsRedis interface.
type MockReadRestaurantsRedis struct {
	ctrl     *gomock.Controller
	recorder *MockReadRestaurantsRedisMockRecorder
	isgomock struct{}
}

// MockReadRestaurantsRedisMockRecorder is the mock recorder for MockReadRestaurantsRedis.
type MockReadRestaurantsRedisMockRecorder struct {
	mock *MockReadRestaurantsRedis
}

// NewMockReadRestaurantsRedis creates a new mock instance.
func NewMockReadRestaurantsRedis(ctrl *gomock.Controller) *MockReadRestaurantsRedis {
	mock := &MockReadRestaurantsRedis{ctrl: ctrl}
	mock.recorder = &MockReadRestaurantsRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadRestaurantsRedis) EXPECT() *MockReadRestaurantsRedisMockRecorder {
	return m.recorder
}

// ReadRestaurant mocks base method.
func (m *MockReadRestaurantsRedis) ReadRestaurant(ctx context.Context, id string) (*aggregates.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurant", ctx, id)
	ret0, _ := ret[0].(*aggregates.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurant indicates an expected call of ReadRestaurant.
func (mr *MockReadRestaurantsRedisMockRecorder) ReadRestaurant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurant", reflect.TypeOf((*MockReadRestaurantsRedis)(nil).ReadRestaurant), ctx, id)
}

// MockSetRestaurantsRedis is a mock of SetRestaurantsRedis interface.
type MockSetRestaurantsRedis struct {
	ctrl     *gomock.Controller
	recorder *MockSetRestaurantsRedisMockRecorder
	isgomock struct{}
}

// MockSetRestaurantsRedisMockRecorder is the mock recorder for MockSetRestaurantsRedis.
type MockSetRestaurantsRedisMockRecorder struct {
	mock *MockSetRestaurantsRedis
}

// NewMockSetRestaurantsRedis creates a new mock instance.
func NewMockSetRestaurantsRedis(ctrl *gomock.Controller) *MockSetRestaurantsRedis {
	mock := &MockSetRestaurantsRedis{ctrl: ctrl}
	mock.recorder = &MockSetRestaurantsRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetRestaurantsRedis) EXPECT() *MockSetRestaurantsRedisMockRecorder {
	return m.recorder
}

// DeleteRestaurant mocks base method.
func (m *MockSetRestaurantsRedis) DeleteRestaurant(ctx context.Context, restaurant *aggregates.Restaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurant", ctx, restaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurant indicates an expected call of DeleteRestaurant.
func (mr *MockSetRestaurantsRedisMockRecorder) DeleteRestaurant(ctx, restaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurant", reflect.TypeOf((*MockSetRestaurantsRedis)(nil).DeleteRestaurant), ctx, restaurant)
}

// SetRestaurant mocks base method.
func (m *MockSetRestaurantsRedis) SetRestaurant(ctx context.Context, restaurant *aggregates.Restaurant, timeOut time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRestaurant", ctx, restaurant, timeOut)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRestaurant indicates an expected call of SetRestaurant.
func (mr *MockSetRestaurantsRedisMockRecorder) SetRestaurant(ctx, restaurant, timeOut any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRestaurant", reflect.TypeOf((*MockSetRestaurantsRedis)(nil).SetRestaurant), ctx, restaurant, timeOut)
}
