// Code generated by MockGen. DO NOT EDIT.
// Source: restaurants_mongo.go
//
// Generated by this command:
//
//	mockgen -source=restaurants_mongo.go -destination=./mocks/restaurants_mongo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	aggregates "github.com/Leon180/go-event-driven-microservices/internal/services/read_restaurants/internal/restaurants/aggregates"
	dtos "github.com/Leon180/go-event-driven-microservices/internal/services/read_restaurants/internal/restaurants/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchRestaurantsMongo is a mock of SearchRestaurantsMongo interface.
type MockSearchRestaurantsMongo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRestaurantsMongoMockRecorder
	isgomock struct{}
}

// MockSearchRestaurantsMongoMockRecorder is the mock recorder for MockSearchRestaurantsMongo.
type MockSearchRestaurantsMongoMockRecorder struct {
	mock *MockSearchRestaurantsMongo
}

// NewMockSearchRestaurantsMongo creates a new mock instance.
func NewMockSearchRestaurantsMongo(ctrl *gomock.Controller) *MockSearchRestaurantsMongo {
	mock := &MockSearchRestaurantsMongo{ctrl: ctrl}
	mock.recorder = &MockSearchRestaurantsMongoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRestaurantsMongo) EXPECT() *MockSearchRestaurantsMongoMockRecorder {
	return m.recorder
}

// SearchRestaurants mocks base method.
func (m *MockSearchRestaurantsMongo) SearchRestaurants(ctx context.Context, searchRestaurants *dtos.SearchRestaurants) (aggregates.Restaurants, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRestaurants", ctx, searchRestaurants)
	ret0, _ := ret[0].(aggregates.Restaurants)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRestaurants indicates an expected call of SearchRestaurants.
func (mr *MockSearchRestaurantsMongoMockRecorder) SearchRestaurants(ctx, searchRestaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRestaurants", reflect.TypeOf((*MockSearchRestaurantsMongo)(nil).SearchRestaurants), ctx, searchRestaurants)
}

// MockReadRestaurantsMongo is a mock of ReadRestaurantsMongo interface.
type MockReadRestaurantsMongo struct {
	ctrl     *gomock.Controller
	recorder *MockReadRestaurantsMongoMockRecorder
	isgomock struct{}
}

// MockReadRestaurantsMongoMockRecorder is the mock recorder for MockReadRestaurantsMongo.
type MockReadRestaurantsMongoMockRecorder struct {
	mock *MockReadRestaurantsMongo
}

// NewMockReadRestaurantsMongo creates a new mock instance.
func NewMockReadRestaurantsMongo(ctrl *gomock.Controller) *MockReadRestaurantsMongo {
	mock := &MockReadRestaurantsMongo{ctrl: ctrl}
	mock.recorder = &MockReadRestaurantsMongoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadRestaurantsMongo) EXPECT() *MockReadRestaurantsMongoMockRecorder {
	return m.recorder
}

// ReadRestaurant mocks base method.
func (m *MockReadRestaurantsMongo) ReadRestaurant(ctx context.Context, id string) (*aggregates.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRestaurant", ctx, id)
	ret0, _ := ret[0].(*aggregates.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRestaurant indicates an expected call of ReadRestaurant.
func (mr *MockReadRestaurantsMongoMockRecorder) ReadRestaurant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRestaurant", reflect.TypeOf((*MockReadRestaurantsMongo)(nil).ReadRestaurant), ctx, id)
}

// MockUpdateRestaurantsMongo is a mock of UpdateRestaurantsMongo interface.
type MockUpdateRestaurantsMongo struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateRestaurantsMongoMockRecorder
	isgomock struct{}
}

// MockUpdateRestaurantsMongoMockRecorder is the mock recorder for MockUpdateRestaurantsMongo.
type MockUpdateRestaurantsMongoMockRecorder struct {
	mock *MockUpdateRestaurantsMongo
}

// NewMockUpdateRestaurantsMongo creates a new mock instance.
func NewMockUpdateRestaurantsMongo(ctrl *gomock.Controller) *MockUpdateRestaurantsMongo {
	mock := &MockUpdateRestaurantsMongo{ctrl: ctrl}
	mock.recorder = &MockUpdateRestaurantsMongoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateRestaurantsMongo) EXPECT() *MockUpdateRestaurantsMongoMockRecorder {
	return m.recorder
}

// CreateRestaurants mocks base method.
func (m *MockUpdateRestaurantsMongo) CreateRestaurants(ctx context.Context, restaurants aggregates.Restaurants) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurants", ctx, restaurants)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRestaurants indicates an expected call of CreateRestaurants.
func (mr *MockUpdateRestaurantsMongoMockRecorder) CreateRestaurants(ctx, restaurants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurants", reflect.TypeOf((*MockUpdateRestaurantsMongo)(nil).CreateRestaurants), ctx, restaurants)
}

// DeleteRestaurants mocks base method.
func (m *MockUpdateRestaurantsMongo) DeleteRestaurants(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurants", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurants indicates an expected call of DeleteRestaurants.
func (mr *MockUpdateRestaurantsMongoMockRecorder) DeleteRestaurants(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurants", reflect.TypeOf((*MockUpdateRestaurantsMongo)(nil).DeleteRestaurants), ctx, ids)
}

// UpdateRestaurant mocks base method.
func (m *MockUpdateRestaurantsMongo) UpdateRestaurant(ctx context.Context, restaurant *aggregates.Restaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurant", ctx, restaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurant indicates an expected call of UpdateRestaurant.
func (mr *MockUpdateRestaurantsMongoMockRecorder) UpdateRestaurant(ctx, restaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurant", reflect.TypeOf((*MockUpdateRestaurantsMongo)(nil).UpdateRestaurant), ctx, restaurant)
}
