// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: restaurants.proto

// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative restaurants.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRestaurantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=RestaurantId,proto3" json:"RestaurantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantReq) Reset() {
	*x = GetRestaurantReq{}
	mi := &file_restaurants_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantReq) ProtoMessage() {}

func (x *GetRestaurantReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantReq.ProtoReflect.Descriptor instead.
func (*GetRestaurantReq) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{0}
}

func (x *GetRestaurantReq) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

type GetRestaurantBranchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchId      string                 `protobuf:"bytes,1,opt,name=BranchId,proto3" json:"BranchId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantBranchReq) Reset() {
	*x = GetRestaurantBranchReq{}
	mi := &file_restaurants_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantBranchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantBranchReq) ProtoMessage() {}

func (x *GetRestaurantBranchReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantBranchReq.ProtoReflect.Descriptor instead.
func (*GetRestaurantBranchReq) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{1}
}

func (x *GetRestaurantBranchReq) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

type SearchRestaurantsReq struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	NameFilter              *string                `protobuf:"bytes,1,opt,name=NameFilter,proto3,oneof" json:"NameFilter,omitempty"`
	NamePreciseSearch       bool                   `protobuf:"varint,2,opt,name=NamePreciseSearch,proto3" json:"NamePreciseSearch,omitempty"`
	BranchID                *string                `protobuf:"bytes,3,opt,name=BranchID,proto3,oneof" json:"BranchID,omitempty"`
	DescriptionFilter       *string                `protobuf:"bytes,4,opt,name=DescriptionFilter,proto3,oneof" json:"DescriptionFilter,omitempty"`
	CityFilter              []string               `protobuf:"bytes,5,rep,name=CityFilter,proto3" json:"CityFilter,omitempty"`
	CountryFilter           []string               `protobuf:"bytes,6,rep,name=CountryFilter,proto3" json:"CountryFilter,omitempty"`
	MaxPriceFilter          *int32                 `protobuf:"varint,7,opt,name=MaxPriceFilter,proto3,oneof" json:"MaxPriceFilter,omitempty"`
	MinPriceFilter          *int32                 `protobuf:"varint,8,opt,name=MinPriceFilter,proto3,oneof" json:"MinPriceFilter,omitempty"`
	CategoryFilter          []string               `protobuf:"bytes,9,rep,name=CategoryFilter,proto3" json:"CategoryFilter,omitempty"`
	TableAvailableWeek      []int32                `protobuf:"varint,10,rep,packed,name=TableAvailableWeek,proto3" json:"TableAvailableWeek,omitempty"`
	TableAvailableStartTime *string                `protobuf:"bytes,11,opt,name=TableAvailableStartTime,proto3,oneof" json:"TableAvailableStartTime,omitempty"`
	TableAvailableEndTime   *string                `protobuf:"bytes,12,opt,name=TableAvailableEndTime,proto3,oneof" json:"TableAvailableEndTime,omitempty"`
	OrderBy                 []*OrderBy             `protobuf:"bytes,13,rep,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	Pagination              *Pagination            `protobuf:"bytes,14,opt,name=Pagination,proto3,oneof" json:"Pagination,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SearchRestaurantsReq) Reset() {
	*x = SearchRestaurantsReq{}
	mi := &file_restaurants_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRestaurantsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRestaurantsReq) ProtoMessage() {}

func (x *SearchRestaurantsReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRestaurantsReq.ProtoReflect.Descriptor instead.
func (*SearchRestaurantsReq) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRestaurantsReq) GetNameFilter() string {
	if x != nil && x.NameFilter != nil {
		return *x.NameFilter
	}
	return ""
}

func (x *SearchRestaurantsReq) GetNamePreciseSearch() bool {
	if x != nil {
		return x.NamePreciseSearch
	}
	return false
}

func (x *SearchRestaurantsReq) GetBranchID() string {
	if x != nil && x.BranchID != nil {
		return *x.BranchID
	}
	return ""
}

func (x *SearchRestaurantsReq) GetDescriptionFilter() string {
	if x != nil && x.DescriptionFilter != nil {
		return *x.DescriptionFilter
	}
	return ""
}

func (x *SearchRestaurantsReq) GetCityFilter() []string {
	if x != nil {
		return x.CityFilter
	}
	return nil
}

func (x *SearchRestaurantsReq) GetCountryFilter() []string {
	if x != nil {
		return x.CountryFilter
	}
	return nil
}

func (x *SearchRestaurantsReq) GetMaxPriceFilter() int32 {
	if x != nil && x.MaxPriceFilter != nil {
		return *x.MaxPriceFilter
	}
	return 0
}

func (x *SearchRestaurantsReq) GetMinPriceFilter() int32 {
	if x != nil && x.MinPriceFilter != nil {
		return *x.MinPriceFilter
	}
	return 0
}

func (x *SearchRestaurantsReq) GetCategoryFilter() []string {
	if x != nil {
		return x.CategoryFilter
	}
	return nil
}

func (x *SearchRestaurantsReq) GetTableAvailableWeek() []int32 {
	if x != nil {
		return x.TableAvailableWeek
	}
	return nil
}

func (x *SearchRestaurantsReq) GetTableAvailableStartTime() string {
	if x != nil && x.TableAvailableStartTime != nil {
		return *x.TableAvailableStartTime
	}
	return ""
}

func (x *SearchRestaurantsReq) GetTableAvailableEndTime() string {
	if x != nil && x.TableAvailableEndTime != nil {
		return *x.TableAvailableEndTime
	}
	return ""
}

func (x *SearchRestaurantsReq) GetOrderBy() []*OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *SearchRestaurantsReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=Direction,proto3" json:"Direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_restaurants_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{3}
}

func (x *OrderBy) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OrderBy) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_restaurants_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Restaurants struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*Restaurant          `protobuf:"bytes,1,rep,name=Restaurants,proto3" json:"Restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurants) Reset() {
	*x = Restaurants{}
	mi := &file_restaurants_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurants) ProtoMessage() {}

func (x *Restaurants) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurants.ProtoReflect.Descriptor instead.
func (*Restaurants) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{5}
}

func (x *Restaurants) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	ActiveStatus  bool                   `protobuf:"varint,4,opt,name=ActiveStatus,proto3" json:"ActiveStatus,omitempty"`
	Branches      []*Branch              `protobuf:"bytes,5,rep,name=Branches,proto3" json:"Branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_restaurants_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{6}
}

func (x *Restaurant) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Restaurant) GetActiveStatus() bool {
	if x != nil {
		return x.ActiveStatus
	}
	return false
}

func (x *Restaurant) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Address       *Address               `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	PriceRange    *PriceRange            `protobuf:"bytes,5,opt,name=PriceRange,proto3" json:"PriceRange,omitempty"`
	Categories    []*Category            `protobuf:"bytes,6,rep,name=Categories,proto3" json:"Categories,omitempty"`
	Availables    []*Available           `protobuf:"bytes,7,rep,name=Availables,proto3" json:"Availables,omitempty"`
	Tables        []*Table               `protobuf:"bytes,8,rep,name=Tables,proto3" json:"Tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_restaurants_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{7}
}

func (x *Branch) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Branch) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Branch) GetPriceRange() *PriceRange {
	if x != nil {
		return x.PriceRange
	}
	return nil
}

func (x *Branch) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Branch) GetAvailables() []*Available {
	if x != nil {
		return x.Availables
	}
	return nil
}

func (x *Branch) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=Street,proto3" json:"Street,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	PostalCode    string                 `protobuf:"bytes,4,opt,name=PostalCode,proto3" json:"PostalCode,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=Country,proto3" json:"Country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_restaurants_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{8}
}

func (x *Address) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type PriceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MinPrice      int32                  `protobuf:"varint,2,opt,name=MinPrice,proto3" json:"MinPrice,omitempty"`
	MaxPrice      int32                  `protobuf:"varint,3,opt,name=MaxPrice,proto3" json:"MaxPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRange) Reset() {
	*x = PriceRange{}
	mi := &file_restaurants_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRange) ProtoMessage() {}

func (x *PriceRange) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRange.ProtoReflect.Descriptor instead.
func (*PriceRange) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{9}
}

func (x *PriceRange) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *PriceRange) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *PriceRange) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_restaurants_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{10}
}

func (x *Category) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Available struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Weekday       int32                  `protobuf:"varint,2,opt,name=Weekday,proto3" json:"Weekday,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Available) Reset() {
	*x = Available{}
	mi := &file_restaurants_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Available) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Available) ProtoMessage() {}

func (x *Available) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Available.ProtoReflect.Descriptor instead.
func (*Available) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{11}
}

func (x *Available) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Available) GetWeekday() int32 {
	if x != nil {
		return x.Weekday
	}
	return 0
}

func (x *Available) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Available) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_restaurants_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_restaurants_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_restaurants_proto_rawDescGZIP(), []int{12}
}

func (x *Table) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Table) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

var File_restaurants_proto protoreflect.FileDescriptor

const file_restaurants_proto_rawDesc = "" +
	"\n" +
	"\x11restaurants.proto\x12\bprotobuf\"6\n" +
	"\x10GetRestaurantReq\x12\"\n" +
	"\fRestaurantId\x18\x01 \x01(\tR\fRestaurantId\"4\n" +
	"\x16GetRestaurantBranchReq\x12\x1a\n" +
	"\bBranchId\x18\x01 \x01(\tR\bBranchId\"\xb4\x06\n" +
	"\x14SearchRestaurantsReq\x12#\n" +
	"\n" +
	"NameFilter\x18\x01 \x01(\tH\x00R\n" +
	"NameFilter\x88\x01\x01\x12,\n" +
	"\x11NamePreciseSearch\x18\x02 \x01(\bR\x11NamePreciseSearch\x12\x1f\n" +
	"\bBranchID\x18\x03 \x01(\tH\x01R\bBranchID\x88\x01\x01\x121\n" +
	"\x11DescriptionFilter\x18\x04 \x01(\tH\x02R\x11DescriptionFilter\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"CityFilter\x18\x05 \x03(\tR\n" +
	"CityFilter\x12$\n" +
	"\rCountryFilter\x18\x06 \x03(\tR\rCountryFilter\x12+\n" +
	"\x0eMaxPriceFilter\x18\a \x01(\x05H\x03R\x0eMaxPriceFilter\x88\x01\x01\x12+\n" +
	"\x0eMinPriceFilter\x18\b \x01(\x05H\x04R\x0eMinPriceFilter\x88\x01\x01\x12&\n" +
	"\x0eCategoryFilter\x18\t \x03(\tR\x0eCategoryFilter\x12.\n" +
	"\x12TableAvailableWeek\x18\n" +
	" \x03(\x05R\x12TableAvailableWeek\x12=\n" +
	"\x17TableAvailableStartTime\x18\v \x01(\tH\x05R\x17TableAvailableStartTime\x88\x01\x01\x129\n" +
	"\x15TableAvailableEndTime\x18\f \x01(\tH\x06R\x15TableAvailableEndTime\x88\x01\x01\x12+\n" +
	"\aOrderBy\x18\r \x03(\v2\x11.protobuf.OrderByR\aOrderBy\x129\n" +
	"\n" +
	"Pagination\x18\x0e \x01(\v2\x14.protobuf.PaginationH\aR\n" +
	"Pagination\x88\x01\x01B\r\n" +
	"\v_NameFilterB\v\n" +
	"\t_BranchIDB\x14\n" +
	"\x12_DescriptionFilterB\x11\n" +
	"\x0f_MaxPriceFilterB\x11\n" +
	"\x0f_MinPriceFilterB\x1a\n" +
	"\x18_TableAvailableStartTimeB\x18\n" +
	"\x16_TableAvailableEndTimeB\r\n" +
	"\v_Pagination\"=\n" +
	"\aOrderBy\x12\x14\n" +
	"\x05Field\x18\x01 \x01(\tR\x05Field\x12\x1c\n" +
	"\tDirection\x18\x02 \x01(\tR\tDirection\"<\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04Page\x18\x01 \x01(\x05R\x04Page\x12\x1a\n" +
	"\bPageSize\x18\x02 \x01(\x05R\bPageSize\"E\n" +
	"\vRestaurants\x126\n" +
	"\vRestaurants\x18\x01 \x03(\v2\x14.protobuf.RestaurantR\vRestaurants\"\xa4\x01\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\"\n" +
	"\fActiveStatus\x18\x04 \x01(\bR\fActiveStatus\x12,\n" +
	"\bBranches\x18\x05 \x03(\v2\x10.protobuf.BranchR\bBranches\"\xc3\x02\n" +
	"\x06Branch\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12+\n" +
	"\aAddress\x18\x04 \x01(\v2\x11.protobuf.AddressR\aAddress\x124\n" +
	"\n" +
	"PriceRange\x18\x05 \x01(\v2\x14.protobuf.PriceRangeR\n" +
	"PriceRange\x122\n" +
	"\n" +
	"Categories\x18\x06 \x03(\v2\x12.protobuf.CategoryR\n" +
	"Categories\x123\n" +
	"\n" +
	"Availables\x18\a \x03(\v2\x13.protobuf.AvailableR\n" +
	"Availables\x12'\n" +
	"\x06Tables\x18\b \x03(\v2\x0f.protobuf.TableR\x06Tables\"\x7f\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Street\x18\x02 \x01(\tR\x06Street\x12\x12\n" +
	"\x04City\x18\x03 \x01(\tR\x04City\x12\x1e\n" +
	"\n" +
	"PostalCode\x18\x04 \x01(\tR\n" +
	"PostalCode\x12\x18\n" +
	"\aCountry\x18\x05 \x01(\tR\aCountry\"T\n" +
	"\n" +
	"PriceRange\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bMinPrice\x18\x02 \x01(\x05R\bMinPrice\x12\x1a\n" +
	"\bMaxPrice\x18\x03 \x01(\x05R\bMaxPrice\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"m\n" +
	"\tAvailable\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aWeekday\x18\x02 \x01(\x05R\aWeekday\x12\x1c\n" +
	"\tStartTime\x18\x03 \x01(\tR\tStartTime\x12\x18\n" +
	"\aEndTime\x18\x04 \x01(\tR\aEndTime\"3\n" +
	"\x05Table\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bCapacity\x18\x02 \x01(\x05R\bCapacity2Y\n" +
	"\x14GetRestaurantService\x12A\n" +
	"\rGetRestaurant\x12\x1a.protobuf.GetRestaurantReq\x1a\x14.protobuf.Restaurant2k\n" +
	"\x1aGetRestaurantBranchService\x12M\n" +
	"\x13GetRestaurantBranch\x12 .protobuf.GetRestaurantBranchReq\x1a\x14.protobuf.Restaurant2f\n" +
	"\x18SearchRestaurantsService\x12J\n" +
	"\x11SearchRestaurants\x12\x1e.protobuf.SearchRestaurantsReq\x1a\x15.protobuf.RestaurantsB\rZ\v./;protobufb\x06proto3"

var (
	file_restaurants_proto_rawDescOnce sync.Once
	file_restaurants_proto_rawDescData []byte
)

func file_restaurants_proto_rawDescGZIP() []byte {
	file_restaurants_proto_rawDescOnce.Do(func() {
		file_restaurants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurants_proto_rawDesc), len(file_restaurants_proto_rawDesc)))
	})
	return file_restaurants_proto_rawDescData
}

var file_restaurants_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_restaurants_proto_goTypes = []any{
	(*GetRestaurantReq)(nil),       // 0: protobuf.GetRestaurantReq
	(*GetRestaurantBranchReq)(nil), // 1: protobuf.GetRestaurantBranchReq
	(*SearchRestaurantsReq)(nil),   // 2: protobuf.SearchRestaurantsReq
	(*OrderBy)(nil),                // 3: protobuf.OrderBy
	(*Pagination)(nil),             // 4: protobuf.Pagination
	(*Restaurants)(nil),            // 5: protobuf.Restaurants
	(*Restaurant)(nil),             // 6: protobuf.Restaurant
	(*Branch)(nil),                 // 7: protobuf.Branch
	(*Address)(nil),                // 8: protobuf.Address
	(*PriceRange)(nil),             // 9: protobuf.PriceRange
	(*Category)(nil),               // 10: protobuf.Category
	(*Available)(nil),              // 11: protobuf.Available
	(*Table)(nil),                  // 12: protobuf.Table
}
var file_restaurants_proto_depIdxs = []int32{
	3,  // 0: protobuf.SearchRestaurantsReq.OrderBy:type_name -> protobuf.OrderBy
	4,  // 1: protobuf.SearchRestaurantsReq.Pagination:type_name -> protobuf.Pagination
	6,  // 2: protobuf.Restaurants.Restaurants:type_name -> protobuf.Restaurant
	7,  // 3: protobuf.Restaurant.Branches:type_name -> protobuf.Branch
	8,  // 4: protobuf.Branch.Address:type_name -> protobuf.Address
	9,  // 5: protobuf.Branch.PriceRange:type_name -> protobuf.PriceRange
	10, // 6: protobuf.Branch.Categories:type_name -> protobuf.Category
	11, // 7: protobuf.Branch.Availables:type_name -> protobuf.Available
	12, // 8: protobuf.Branch.Tables:type_name -> protobuf.Table
	0,  // 9: protobuf.GetRestaurantService.GetRestaurant:input_type -> protobuf.GetRestaurantReq
	1,  // 10: protobuf.GetRestaurantBranchService.GetRestaurantBranch:input_type -> protobuf.GetRestaurantBranchReq
	2,  // 11: protobuf.SearchRestaurantsService.SearchRestaurants:input_type -> protobuf.SearchRestaurantsReq
	6,  // 12: protobuf.GetRestaurantService.GetRestaurant:output_type -> protobuf.Restaurant
	6,  // 13: protobuf.GetRestaurantBranchService.GetRestaurantBranch:output_type -> protobuf.Restaurant
	5,  // 14: protobuf.SearchRestaurantsService.SearchRestaurants:output_type -> protobuf.Restaurants
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_restaurants_proto_init() }
func file_restaurants_proto_init() {
	if File_restaurants_proto != nil {
		return
	}
	file_restaurants_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurants_proto_rawDesc), len(file_restaurants_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_restaurants_proto_goTypes,
		DependencyIndexes: file_restaurants_proto_depIdxs,
		MessageInfos:      file_restaurants_proto_msgTypes,
	}.Build()
	File_restaurants_proto = out.File
	file_restaurants_proto_goTypes = nil
	file_restaurants_proto_depIdxs = nil
}
